// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_logger_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\plugins\\code_shared_logger_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/plugins__code_shared_logger_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("create_logger [immutability] argset_0", () => {
  const __args = [0];
  const before = JSON.stringify(__args);
  const result = __attempt("create_logger", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("create_logger [immutability] argset_1", () => {
  const __args = [-1];
  const before = JSON.stringify(__args);
  const result = __attempt("create_logger", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("create_logger [immutability] argset_2", () => {
  const __args = [42];
  const before = JSON.stringify(__args);
  const result = __attempt("create_logger", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("create_logger [immutability] argset_3", () => {
  const __args = [3.14];
  const before = JSON.stringify(__args);
  const result = __attempt("create_logger", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("create_logger [immutability] argset_4", () => {
  const __args = [42];
  const before = JSON.stringify(__args);
  const result = __attempt("create_logger", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("create_logger [edge_safety] edge_0", () => {
  const __args = [0];
  try {
    __call("create_logger", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("create_logger [edge_safety] edge_1", () => {
  const __args = [-1];
  try {
    __call("create_logger", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("create_logger [edge_safety] edge_2", () => {
  const __args = [NaN];
  try {
    __call("create_logger", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("create_logger [edge_safety] edge_3", () => {
  const __args = [Infinity];
  try {
    __call("create_logger", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("create_logger [edge_safety] edge_4", () => {
  const __args = [-Infinity];
  try {
    __call("create_logger", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("create_logger [edge_safety] edge_5", () => {
  const __args = [65536];
  try {
    __call("create_logger", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("create_metrics [edge_safety] edge_0", () => {
  const __args = [];
  try {
    __call("create_metrics", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

