// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_intent_registry_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\plugins\\code_shared_intent_registry_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/plugins__code_shared_intent_registry_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("register [determinism] argset_0", () => {
  const __args = ["seed_value", "seed_value"];
  const first = __attempt("register", __args);
  const second = __attempt("register", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("register [immutability] argset_0", () => {
  const __args = ["seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("register", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("register [determinism] argset_1", () => {
  const __args = ["seed_value", "seed_value"];
  const first = __attempt("register", __args);
  const second = __attempt("register", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("register [immutability] argset_1", () => {
  const __args = ["seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("register", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("register [edge_safety] edge_0", () => {
  const __args = [null, null];
  try {
    __call("register", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("register [edge_safety] edge_1", () => {
  const __args = [null, "seed_value"];
  try {
    __call("register", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("register [edge_safety] edge_2", () => {
  const __args = [undefined, "seed_value"];
  try {
    __call("register", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("register [edge_safety] edge_3", () => {
  const __args = ["seed_value", null];
  try {
    __call("register", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("register [edge_safety] edge_4", () => {
  const __args = ["seed_value", undefined];
  try {
    __call("register", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("lookup [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("lookup", __args);
  const second = __attempt("lookup", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("lookup [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("lookup", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("lookup [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("lookup", __args);
  const second = __attempt("lookup", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("lookup [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("lookup", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("lookup [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("lookup", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("lookup [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("lookup", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("get [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("get", __args);
  const second = __attempt("get", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("get [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("get", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("get [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("get", __args);
  const second = __attempt("get", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("get [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("get", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("get [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("get", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("get [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("get", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("all [determinism] argset_0", () => {
  const __args = [];
  const first = __attempt("all", __args);
  const second = __attempt("all", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("all [edge_safety] edge_0", () => {
  const __args = [];
  try {
    __call("all", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

