// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_runner_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\plugins\\code_shared_runner_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/plugins__code_shared_runner_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("execute [determinism] argset_0", () => {
  const __args = [{}, {}];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_0", () => {
  const __args = [{}, {}];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_0", () => {
  const __args = [{}, {}];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][2];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("execute [determinism] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][5];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("execute [determinism] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][8];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("execute [edge_safety] edge_0", () => {
  const __args = [{}, {}];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_1", () => {
  const __args = [{}, {"a": 1}];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_2", () => {
  const __args = [null, {"a": 1}];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_3", () => {
  const __args = [{"a": 1}, {}];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_4", () => {
  const __args = [{"a": 1}, null];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeTask [determinism] argset_0", () => {
  const __args = [{}, {}];
  const first = __attempt("executeTask", __args);
  const second = __attempt("executeTask", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeTask [immutability] argset_0", () => {
  const __args = [{}, {}];
  const before = JSON.stringify(__args);
  const result = __attempt("executeTask", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeTask [snapshot] argset_0", () => {
  const __args = [{}, {}];
  const actual = JSON.stringify(__attempt("executeTask", __args));
  const stored = __snapshots["executeTask"] && __snapshots["executeTask"][2];
  if (__capture || stored === undefined) {
    __snapshots["executeTask"] = __snapshots["executeTask"] || {};
    __snapshots["executeTask"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("executeTask [determinism] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const first = __attempt("executeTask", __args);
  const second = __attempt("executeTask", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeTask [immutability] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("executeTask", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeTask [snapshot] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const actual = JSON.stringify(__attempt("executeTask", __args));
  const stored = __snapshots["executeTask"] && __snapshots["executeTask"][5];
  if (__capture || stored === undefined) {
    __snapshots["executeTask"] = __snapshots["executeTask"] || {};
    __snapshots["executeTask"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("executeTask [determinism] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const first = __attempt("executeTask", __args);
  const second = __attempt("executeTask", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeTask [immutability] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("executeTask", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeTask [snapshot] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const actual = JSON.stringify(__attempt("executeTask", __args));
  const stored = __snapshots["executeTask"] && __snapshots["executeTask"][8];
  if (__capture || stored === undefined) {
    __snapshots["executeTask"] = __snapshots["executeTask"] || {};
    __snapshots["executeTask"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("executeTask [edge_safety] edge_0", () => {
  const __args = [{}, {}];
  try {
    __call("executeTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeTask [edge_safety] edge_1", () => {
  const __args = [{}, {"a": 1}];
  try {
    __call("executeTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeTask [edge_safety] edge_2", () => {
  const __args = [null, {"a": 1}];
  try {
    __call("executeTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeTask [edge_safety] edge_3", () => {
  const __args = [{"a": 1}, {}];
  try {
    __call("executeTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeTask [edge_safety] edge_4", () => {
  const __args = [{"a": 1}, null];
  try {
    __call("executeTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveInput [determinism] argset_0", () => {
  const __args = [{}, {}];
  const first = __attempt("resolveInput", __args);
  const second = __attempt("resolveInput", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveInput [immutability] argset_0", () => {
  const __args = [{}, {}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveInput", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveInput [snapshot] argset_0", () => {
  const __args = [{}, {}];
  const actual = JSON.stringify(__attempt("resolveInput", __args));
  const stored = __snapshots["resolveInput"] && __snapshots["resolveInput"][2];
  if (__capture || stored === undefined) {
    __snapshots["resolveInput"] = __snapshots["resolveInput"] || {};
    __snapshots["resolveInput"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("resolveInput [determinism] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const first = __attempt("resolveInput", __args);
  const second = __attempt("resolveInput", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveInput [immutability] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveInput", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveInput [snapshot] argset_1", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const actual = JSON.stringify(__attempt("resolveInput", __args));
  const stored = __snapshots["resolveInput"] && __snapshots["resolveInput"][5];
  if (__capture || stored === undefined) {
    __snapshots["resolveInput"] = __snapshots["resolveInput"] || {};
    __snapshots["resolveInput"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("resolveInput [determinism] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const first = __attempt("resolveInput", __args);
  const second = __attempt("resolveInput", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveInput [immutability] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveInput", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveInput [snapshot] argset_2", () => {
  const __args = [{"a": 1}, {"a": 1}];
  const actual = JSON.stringify(__attempt("resolveInput", __args));
  const stored = __snapshots["resolveInput"] && __snapshots["resolveInput"][8];
  if (__capture || stored === undefined) {
    __snapshots["resolveInput"] = __snapshots["resolveInput"] || {};
    __snapshots["resolveInput"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("resolveInput [edge_safety] edge_0", () => {
  const __args = [{}, {}];
  try {
    __call("resolveInput", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveInput [edge_safety] edge_1", () => {
  const __args = [{}, {"a": 1}];
  try {
    __call("resolveInput", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveInput [edge_safety] edge_2", () => {
  const __args = [null, {"a": 1}];
  try {
    __call("resolveInput", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveInput [edge_safety] edge_3", () => {
  const __args = [{"a": 1}, {}];
  try {
    __call("resolveInput", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveInput [edge_safety] edge_4", () => {
  const __args = [{"a": 1}, null];
  try {
    __call("resolveInput", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveSource [determinism] argset_0", () => {
  const __args = ["alpha", {}];
  const first = __attempt("resolveSource", __args);
  const second = __attempt("resolveSource", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveSource [immutability] argset_0", () => {
  const __args = ["alpha", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveSource", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveSource [snapshot] argset_0", () => {
  const __args = ["alpha", {}];
  const actual = JSON.stringify(__attempt("resolveSource", __args));
  const stored = __snapshots["resolveSource"] && __snapshots["resolveSource"][2];
  if (__capture || stored === undefined) {
    __snapshots["resolveSource"] = __snapshots["resolveSource"] || {};
    __snapshots["resolveSource"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("resolveSource [determinism] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const first = __attempt("resolveSource", __args);
  const second = __attempt("resolveSource", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveSource [immutability] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveSource", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveSource [snapshot] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const actual = JSON.stringify(__attempt("resolveSource", __args));
  const stored = __snapshots["resolveSource"] && __snapshots["resolveSource"][5];
  if (__capture || stored === undefined) {
    __snapshots["resolveSource"] = __snapshots["resolveSource"] || {};
    __snapshots["resolveSource"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("resolveSource [determinism] argset_2", () => {
  const __args = ["", {}];
  const first = __attempt("resolveSource", __args);
  const second = __attempt("resolveSource", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveSource [immutability] argset_2", () => {
  const __args = ["", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveSource", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveSource [snapshot] argset_2", () => {
  const __args = ["", {}];
  const actual = JSON.stringify(__attempt("resolveSource", __args));
  const stored = __snapshots["resolveSource"] && __snapshots["resolveSource"][8];
  if (__capture || stored === undefined) {
    __snapshots["resolveSource"] = __snapshots["resolveSource"] || {};
    __snapshots["resolveSource"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("resolveSource [determinism] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const first = __attempt("resolveSource", __args);
  const second = __attempt("resolveSource", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveSource [immutability] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveSource", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveSource [snapshot] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const actual = JSON.stringify(__attempt("resolveSource", __args));
  const stored = __snapshots["resolveSource"] && __snapshots["resolveSource"][11];
  if (__capture || stored === undefined) {
    __snapshots["resolveSource"] = __snapshots["resolveSource"] || {};
    __snapshots["resolveSource"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("resolveSource [determinism] argset_4", () => {
  const __args = ["Alpha42", {}];
  const first = __attempt("resolveSource", __args);
  const second = __attempt("resolveSource", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveSource [immutability] argset_4", () => {
  const __args = ["Alpha42", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveSource", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveSource [snapshot] argset_4", () => {
  const __args = ["Alpha42", {}];
  const actual = JSON.stringify(__attempt("resolveSource", __args));
  const stored = __snapshots["resolveSource"] && __snapshots["resolveSource"][14];
  if (__capture || stored === undefined) {
    __snapshots["resolveSource"] = __snapshots["resolveSource"] || {};
    __snapshots["resolveSource"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("resolveSource [determinism] argset_5", () => {
  const __args = ["", {"a": 1}];
  const first = __attempt("resolveSource", __args);
  const second = __attempt("resolveSource", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveSource [immutability] argset_5", () => {
  const __args = ["", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveSource", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveSource [snapshot] argset_5", () => {
  const __args = ["", {"a": 1}];
  const actual = JSON.stringify(__attempt("resolveSource", __args));
  const stored = __snapshots["resolveSource"] && __snapshots["resolveSource"][17];
  if (__capture || stored === undefined) {
    __snapshots["resolveSource"] = __snapshots["resolveSource"] || {};
    __snapshots["resolveSource"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("resolveSource [edge_safety] edge_0", () => {
  const __args = ["", {}];
  try {
    __call("resolveSource", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveSource [edge_safety] edge_1", () => {
  const __args = ["", {"a": 1}];
  try {
    __call("resolveSource", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveSource [edge_safety] edge_2", () => {
  const __args = [" ", {"a": 1}];
  try {
    __call("resolveSource", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveSource [edge_safety] edge_3", () => {
  const __args = ["\t", {"a": 1}];
  try {
    __call("resolveSource", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveSource [edge_safety] edge_4", () => {
  const __args = ["0", {"a": 1}];
  try {
    __call("resolveSource", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveSource [edge_safety] edge_5", () => {
  const __args = ["null", {"a": 1}];
  try {
    __call("resolveSource", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveSource [edge_safety] edge_6", () => {
  const __args = ["", null];
  try {
    __call("resolveSource", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("topologicalSort [determinism] argset_0", () => {
  const __args = [[]];
  const first = __attempt("topologicalSort", __args);
  const second = __attempt("topologicalSort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topologicalSort [immutability] argset_0", () => {
  const __args = [[]];
  const before = JSON.stringify(__args);
  const result = __attempt("topologicalSort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topologicalSort [snapshot] argset_0", () => {
  const __args = [[]];
  const actual = JSON.stringify(__attempt("topologicalSort", __args));
  const stored = __snapshots["topologicalSort"] && __snapshots["topologicalSort"][2];
  if (__capture || stored === undefined) {
    __snapshots["topologicalSort"] = __snapshots["topologicalSort"] || {};
    __snapshots["topologicalSort"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("topologicalSort [determinism] argset_1", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("topologicalSort", __args);
  const second = __attempt("topologicalSort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topologicalSort [immutability] argset_1", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("topologicalSort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topologicalSort [snapshot] argset_1", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("topologicalSort", __args));
  const stored = __snapshots["topologicalSort"] && __snapshots["topologicalSort"][5];
  if (__capture || stored === undefined) {
    __snapshots["topologicalSort"] = __snapshots["topologicalSort"] || {};
    __snapshots["topologicalSort"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("topologicalSort [determinism] argset_2", () => {
  const __args = [[0]];
  const first = __attempt("topologicalSort", __args);
  const second = __attempt("topologicalSort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topologicalSort [immutability] argset_2", () => {
  const __args = [[0]];
  const before = JSON.stringify(__args);
  const result = __attempt("topologicalSort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topologicalSort [snapshot] argset_2", () => {
  const __args = [[0]];
  const actual = JSON.stringify(__attempt("topologicalSort", __args));
  const stored = __snapshots["topologicalSort"] && __snapshots["topologicalSort"][8];
  if (__capture || stored === undefined) {
    __snapshots["topologicalSort"] = __snapshots["topologicalSort"] || {};
    __snapshots["topologicalSort"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("topologicalSort [determinism] argset_3", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("topologicalSort", __args);
  const second = __attempt("topologicalSort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topologicalSort [immutability] argset_3", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("topologicalSort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topologicalSort [snapshot] argset_3", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("topologicalSort", __args));
  const stored = __snapshots["topologicalSort"] && __snapshots["topologicalSort"][11];
  if (__capture || stored === undefined) {
    __snapshots["topologicalSort"] = __snapshots["topologicalSort"] || {};
    __snapshots["topologicalSort"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("topologicalSort [edge_safety] edge_0", () => {
  const __args = [[]];
  try {
    __call("topologicalSort", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("topologicalSort [edge_safety] edge_1", () => {
  const __args = [[null]];
  try {
    __call("topologicalSort", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [determinism] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value", "seed_value"];
  const first = __attempt("visitTask", __args);
  const second = __attempt("visitTask", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("visitTask [immutability] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("visitTask", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("visitTask [snapshot] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("visitTask", __args));
  const stored = __snapshots["visitTask"] && __snapshots["visitTask"][2];
  if (__capture || stored === undefined) {
    __snapshots["visitTask"] = __snapshots["visitTask"] || {};
    __snapshots["visitTask"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("visitTask [determinism] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value", "seed_value"];
  const first = __attempt("visitTask", __args);
  const second = __attempt("visitTask", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("visitTask [immutability] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("visitTask", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("visitTask [snapshot] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("visitTask", __args));
  const stored = __snapshots["visitTask"] && __snapshots["visitTask"][5];
  if (__capture || stored === undefined) {
    __snapshots["visitTask"] = __snapshots["visitTask"] || {};
    __snapshots["visitTask"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("visitTask [edge_safety] edge_0", () => {
  const __args = [null, null, null, null];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_1", () => {
  const __args = [null, "seed_value", "seed_value", "seed_value"];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_2", () => {
  const __args = [undefined, "seed_value", "seed_value", "seed_value"];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_3", () => {
  const __args = ["seed_value", null, "seed_value", "seed_value"];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_4", () => {
  const __args = ["seed_value", undefined, "seed_value", "seed_value"];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_5", () => {
  const __args = ["seed_value", "seed_value", null, "seed_value"];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_6", () => {
  const __args = ["seed_value", "seed_value", undefined, "seed_value"];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_7", () => {
  const __args = ["seed_value", "seed_value", "seed_value", null];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("visitTask [edge_safety] edge_8", () => {
  const __args = ["seed_value", "seed_value", "seed_value", undefined];
  try {
    __call("visitTask", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("getResults [determinism] argset_0", () => {
  const __args = [];
  const first = __attempt("getResults", __args);
  const second = __attempt("getResults", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("getResults [edge_safety] edge_0", () => {
  const __args = [];
  try {
    __call("getResults", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("getResult [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("getResult", __args);
  const second = __attempt("getResult", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("getResult [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("getResult", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("getResult [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("getResult", __args));
  const stored = __snapshots["getResult"] && __snapshots["getResult"][2];
  if (__capture || stored === undefined) {
    __snapshots["getResult"] = __snapshots["getResult"] || {};
    __snapshots["getResult"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("getResult [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("getResult", __args);
  const second = __attempt("getResult", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("getResult [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("getResult", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("getResult [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("getResult", __args));
  const stored = __snapshots["getResult"] && __snapshots["getResult"][5];
  if (__capture || stored === undefined) {
    __snapshots["getResult"] = __snapshots["getResult"] || {};
    __snapshots["getResult"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("getResult [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("getResult", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("getResult [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("getResult", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

