// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_terminal_renderer_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\plugins\\code_shared_terminal_renderer_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/plugins__code_shared_terminal_renderer_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("activate [determinism] argset_0", () => {
  const __args = [{}];
  const first = __attempt("activate", __args);
  const second = __attempt("activate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("activate [immutability] argset_0", () => {
  const __args = [{}];
  const before = JSON.stringify(__args);
  const result = __attempt("activate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("activate [snapshot] argset_0", () => {
  const __args = [{}];
  const actual = JSON.stringify(__attempt("activate", __args));
  const stored = __snapshots["activate"] && __snapshots["activate"][2];
  if (__capture || stored === undefined) {
    __snapshots["activate"] = __snapshots["activate"] || {};
    __snapshots["activate"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("activate [determinism] argset_1", () => {
  const __args = [{"a": 1}];
  const first = __attempt("activate", __args);
  const second = __attempt("activate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("activate [immutability] argset_1", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("activate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("activate [snapshot] argset_1", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("activate", __args));
  const stored = __snapshots["activate"] && __snapshots["activate"][5];
  if (__capture || stored === undefined) {
    __snapshots["activate"] = __snapshots["activate"] || {};
    __snapshots["activate"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("activate [determinism] argset_2", () => {
  const __args = [{"a": 1}];
  const first = __attempt("activate", __args);
  const second = __attempt("activate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("activate [immutability] argset_2", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("activate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("activate [snapshot] argset_2", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("activate", __args));
  const stored = __snapshots["activate"] && __snapshots["activate"][8];
  if (__capture || stored === undefined) {
    __snapshots["activate"] = __snapshots["activate"] || {};
    __snapshots["activate"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("activate [edge_safety] edge_0", () => {
  const __args = [{}];
  try {
    __call("activate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("activate [edge_safety] edge_1", () => {
  const __args = [null];
  try {
    __call("activate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deactivate [determinism] argset_0", () => {
  const __args = [{}];
  const first = __attempt("deactivate", __args);
  const second = __attempt("deactivate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deactivate [immutability] argset_0", () => {
  const __args = [{}];
  const before = JSON.stringify(__args);
  const result = __attempt("deactivate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deactivate [snapshot] argset_0", () => {
  const __args = [{}];
  const actual = JSON.stringify(__attempt("deactivate", __args));
  const stored = __snapshots["deactivate"] && __snapshots["deactivate"][2];
  if (__capture || stored === undefined) {
    __snapshots["deactivate"] = __snapshots["deactivate"] || {};
    __snapshots["deactivate"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("deactivate [determinism] argset_1", () => {
  const __args = [{"a": 1}];
  const first = __attempt("deactivate", __args);
  const second = __attempt("deactivate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deactivate [immutability] argset_1", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("deactivate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deactivate [snapshot] argset_1", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("deactivate", __args));
  const stored = __snapshots["deactivate"] && __snapshots["deactivate"][5];
  if (__capture || stored === undefined) {
    __snapshots["deactivate"] = __snapshots["deactivate"] || {};
    __snapshots["deactivate"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("deactivate [determinism] argset_2", () => {
  const __args = [{"a": 1}];
  const first = __attempt("deactivate", __args);
  const second = __attempt("deactivate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deactivate [immutability] argset_2", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("deactivate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deactivate [snapshot] argset_2", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("deactivate", __args));
  const stored = __snapshots["deactivate"] && __snapshots["deactivate"][8];
  if (__capture || stored === undefined) {
    __snapshots["deactivate"] = __snapshots["deactivate"] || {};
    __snapshots["deactivate"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("deactivate [edge_safety] edge_0", () => {
  const __args = [{}];
  try {
    __call("deactivate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deactivate [edge_safety] edge_1", () => {
  const __args = [null];
  try {
    __call("deactivate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

