// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_runtime_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\plugins\\code_shared_runtime_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/plugins__code_shared_runtime_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("createWithDefaultBackend [determinism] argset_0", () => {
  const __args = [{}];
  const first = __attempt("createWithDefaultBackend", __args);
  const second = __attempt("createWithDefaultBackend", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("createWithDefaultBackend [immutability] argset_0", () => {
  const __args = [{}];
  const before = JSON.stringify(__args);
  const result = __attempt("createWithDefaultBackend", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("createWithDefaultBackend [snapshot] argset_0", () => {
  const __args = [{}];
  const actual = JSON.stringify(__attempt("createWithDefaultBackend", __args));
  const stored = __snapshots["createWithDefaultBackend"] && __snapshots["createWithDefaultBackend"][2];
  if (__capture || stored === undefined) {
    __snapshots["createWithDefaultBackend"] = __snapshots["createWithDefaultBackend"] || {};
    __snapshots["createWithDefaultBackend"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("createWithDefaultBackend [determinism] argset_1", () => {
  const __args = [{"a": 1}];
  const first = __attempt("createWithDefaultBackend", __args);
  const second = __attempt("createWithDefaultBackend", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("createWithDefaultBackend [immutability] argset_1", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("createWithDefaultBackend", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("createWithDefaultBackend [snapshot] argset_1", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("createWithDefaultBackend", __args));
  const stored = __snapshots["createWithDefaultBackend"] && __snapshots["createWithDefaultBackend"][5];
  if (__capture || stored === undefined) {
    __snapshots["createWithDefaultBackend"] = __snapshots["createWithDefaultBackend"] || {};
    __snapshots["createWithDefaultBackend"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("createWithDefaultBackend [determinism] argset_2", () => {
  const __args = [{"a": 1}];
  const first = __attempt("createWithDefaultBackend", __args);
  const second = __attempt("createWithDefaultBackend", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("createWithDefaultBackend [immutability] argset_2", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("createWithDefaultBackend", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("createWithDefaultBackend [snapshot] argset_2", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("createWithDefaultBackend", __args));
  const stored = __snapshots["createWithDefaultBackend"] && __snapshots["createWithDefaultBackend"][8];
  if (__capture || stored === undefined) {
    __snapshots["createWithDefaultBackend"] = __snapshots["createWithDefaultBackend"] || {};
    __snapshots["createWithDefaultBackend"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("createWithDefaultBackend [edge_safety] edge_0", () => {
  const __args = [{}];
  try {
    __call("createWithDefaultBackend", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("createWithDefaultBackend [edge_safety] edge_1", () => {
  const __args = [null];
  try {
    __call("createWithDefaultBackend", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][2];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("tokenize [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][5];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("tokenize [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][8];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("tokenize [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][11];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("tokenize [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][14];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("tokenize [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][17];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("tokenize [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse [determinism] argset_0", () => {
  const __args = [[]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_0", () => {
  const __args = [[]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_0", () => {
  const __args = [[]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][2];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("parse [determinism] argset_1", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_1", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_1", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][5];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("parse [determinism] argset_2", () => {
  const __args = [[0]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_2", () => {
  const __args = [[0]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_2", () => {
  const __args = [[0]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][8];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("parse [determinism] argset_3", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_3", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_3", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][11];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("parse [edge_safety] edge_0", () => {
  const __args = [[]];
  try {
    __call("parse", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse [edge_safety] edge_1", () => {
  const __args = [[null]];
  try {
    __call("parse", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("compile [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("compile", __args);
  const second = __attempt("compile", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("compile [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("compile", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("compile [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("compile", __args));
  const stored = __snapshots["compile"] && __snapshots["compile"][2];
  if (__capture || stored === undefined) {
    __snapshots["compile"] = __snapshots["compile"] || {};
    __snapshots["compile"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("compile [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("compile", __args);
  const second = __attempt("compile", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("compile [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("compile", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("compile [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("compile", __args));
  const stored = __snapshots["compile"] && __snapshots["compile"][5];
  if (__capture || stored === undefined) {
    __snapshots["compile"] = __snapshots["compile"] || {};
    __snapshots["compile"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("compile [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("compile", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("compile [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("compile", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("process [immutability] argset_0", () => {
  const __args = ["alpha", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("process", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("process [immutability] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("process", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("process [immutability] argset_2", () => {
  const __args = ["", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("process", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("process [immutability] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("process", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("process [immutability] argset_4", () => {
  const __args = ["Alpha42", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("process", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("process [immutability] argset_5", () => {
  const __args = ["", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("process", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("process [edge_safety] edge_0", () => {
  const __args = ["", {}];
  try {
    __call("process", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("process [edge_safety] edge_1", () => {
  const __args = ["", {"a": 1}];
  try {
    __call("process", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("process [edge_safety] edge_2", () => {
  const __args = [" ", {"a": 1}];
  try {
    __call("process", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("process [edge_safety] edge_3", () => {
  const __args = ["\t", {"a": 1}];
  try {
    __call("process", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("process [edge_safety] edge_4", () => {
  const __args = ["0", {"a": 1}];
  try {
    __call("process", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("process [edge_safety] edge_5", () => {
  const __args = ["null", {"a": 1}];
  try {
    __call("process", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("process [edge_safety] edge_6", () => {
  const __args = ["", null];
  try {
    __call("process", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [determinism] argset_0", () => {
  const __args = ["alpha", {}, "seed_value"];
  const first = __attempt("buildInputEnvelope", __args);
  const second = __attempt("buildInputEnvelope", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildInputEnvelope [immutability] argset_0", () => {
  const __args = ["alpha", {}, "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("buildInputEnvelope", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildInputEnvelope [snapshot] argset_0", () => {
  const __args = ["alpha", {}, "seed_value"];
  const actual = JSON.stringify(__attempt("buildInputEnvelope", __args));
  const stored = __snapshots["buildInputEnvelope"] && __snapshots["buildInputEnvelope"][2];
  if (__capture || stored === undefined) {
    __snapshots["buildInputEnvelope"] = __snapshots["buildInputEnvelope"] || {};
    __snapshots["buildInputEnvelope"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("buildInputEnvelope [determinism] argset_1", () => {
  const __args = ["hello world", {"a": 1}, "seed_value"];
  const first = __attempt("buildInputEnvelope", __args);
  const second = __attempt("buildInputEnvelope", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildInputEnvelope [immutability] argset_1", () => {
  const __args = ["hello world", {"a": 1}, "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("buildInputEnvelope", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildInputEnvelope [snapshot] argset_1", () => {
  const __args = ["hello world", {"a": 1}, "seed_value"];
  const actual = JSON.stringify(__attempt("buildInputEnvelope", __args));
  const stored = __snapshots["buildInputEnvelope"] && __snapshots["buildInputEnvelope"][5];
  if (__capture || stored === undefined) {
    __snapshots["buildInputEnvelope"] = __snapshots["buildInputEnvelope"] || {};
    __snapshots["buildInputEnvelope"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("buildInputEnvelope [determinism] argset_2", () => {
  const __args = ["", {}, "seed_value"];
  const first = __attempt("buildInputEnvelope", __args);
  const second = __attempt("buildInputEnvelope", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildInputEnvelope [immutability] argset_2", () => {
  const __args = ["", {}, "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("buildInputEnvelope", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildInputEnvelope [snapshot] argset_2", () => {
  const __args = ["", {}, "seed_value"];
  const actual = JSON.stringify(__attempt("buildInputEnvelope", __args));
  const stored = __snapshots["buildInputEnvelope"] && __snapshots["buildInputEnvelope"][8];
  if (__capture || stored === undefined) {
    __snapshots["buildInputEnvelope"] = __snapshots["buildInputEnvelope"] || {};
    __snapshots["buildInputEnvelope"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("buildInputEnvelope [determinism] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}, "seed_value"];
  const first = __attempt("buildInputEnvelope", __args);
  const second = __attempt("buildInputEnvelope", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildInputEnvelope [immutability] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}, "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("buildInputEnvelope", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildInputEnvelope [snapshot] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}, "seed_value"];
  const actual = JSON.stringify(__attempt("buildInputEnvelope", __args));
  const stored = __snapshots["buildInputEnvelope"] && __snapshots["buildInputEnvelope"][11];
  if (__capture || stored === undefined) {
    __snapshots["buildInputEnvelope"] = __snapshots["buildInputEnvelope"] || {};
    __snapshots["buildInputEnvelope"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("buildInputEnvelope [determinism] argset_4", () => {
  const __args = ["Alpha42", {}, "seed_value"];
  const first = __attempt("buildInputEnvelope", __args);
  const second = __attempt("buildInputEnvelope", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildInputEnvelope [immutability] argset_4", () => {
  const __args = ["Alpha42", {}, "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("buildInputEnvelope", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildInputEnvelope [snapshot] argset_4", () => {
  const __args = ["Alpha42", {}, "seed_value"];
  const actual = JSON.stringify(__attempt("buildInputEnvelope", __args));
  const stored = __snapshots["buildInputEnvelope"] && __snapshots["buildInputEnvelope"][14];
  if (__capture || stored === undefined) {
    __snapshots["buildInputEnvelope"] = __snapshots["buildInputEnvelope"] || {};
    __snapshots["buildInputEnvelope"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("buildInputEnvelope [determinism] argset_5", () => {
  const __args = ["", {"a": 1}, "seed_value"];
  const first = __attempt("buildInputEnvelope", __args);
  const second = __attempt("buildInputEnvelope", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildInputEnvelope [immutability] argset_5", () => {
  const __args = ["", {"a": 1}, "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("buildInputEnvelope", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildInputEnvelope [snapshot] argset_5", () => {
  const __args = ["", {"a": 1}, "seed_value"];
  const actual = JSON.stringify(__attempt("buildInputEnvelope", __args));
  const stored = __snapshots["buildInputEnvelope"] && __snapshots["buildInputEnvelope"][17];
  if (__capture || stored === undefined) {
    __snapshots["buildInputEnvelope"] = __snapshots["buildInputEnvelope"] || {};
    __snapshots["buildInputEnvelope"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("buildInputEnvelope [edge_safety] edge_0", () => {
  const __args = ["", {}, null];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_1", () => {
  const __args = ["", {"a": 1}, "seed_value"];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_2", () => {
  const __args = [" ", {"a": 1}, "seed_value"];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_3", () => {
  const __args = ["\t", {"a": 1}, "seed_value"];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_4", () => {
  const __args = ["0", {"a": 1}, "seed_value"];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_5", () => {
  const __args = ["null", {"a": 1}, "seed_value"];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_6", () => {
  const __args = ["", {}, "seed_value"];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_7", () => {
  const __args = ["", null, "seed_value"];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_8", () => {
  const __args = ["", {"a": 1}, null];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildInputEnvelope [edge_safety] edge_9", () => {
  const __args = ["", {"a": 1}, undefined];
  try {
    __call("buildInputEnvelope", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("attachAstSourceMetadata [determinism] argset_0", () => {
  const __args = ["seed_value", "alpha"];
  const first = __attempt("attachAstSourceMetadata", __args);
  const second = __attempt("attachAstSourceMetadata", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("attachAstSourceMetadata [immutability] argset_0", () => {
  const __args = ["seed_value", "alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("attachAstSourceMetadata", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("attachAstSourceMetadata [snapshot] argset_0", () => {
  const __args = ["seed_value", "alpha"];
  const actual = JSON.stringify(__attempt("attachAstSourceMetadata", __args));
  const stored = __snapshots["attachAstSourceMetadata"] && __snapshots["attachAstSourceMetadata"][2];
  if (__capture || stored === undefined) {
    __snapshots["attachAstSourceMetadata"] = __snapshots["attachAstSourceMetadata"] || {};
    __snapshots["attachAstSourceMetadata"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("attachAstSourceMetadata [determinism] argset_1", () => {
  const __args = ["seed_value", "hello world"];
  const first = __attempt("attachAstSourceMetadata", __args);
  const second = __attempt("attachAstSourceMetadata", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("attachAstSourceMetadata [immutability] argset_1", () => {
  const __args = ["seed_value", "hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("attachAstSourceMetadata", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("attachAstSourceMetadata [snapshot] argset_1", () => {
  const __args = ["seed_value", "hello world"];
  const actual = JSON.stringify(__attempt("attachAstSourceMetadata", __args));
  const stored = __snapshots["attachAstSourceMetadata"] && __snapshots["attachAstSourceMetadata"][5];
  if (__capture || stored === undefined) {
    __snapshots["attachAstSourceMetadata"] = __snapshots["attachAstSourceMetadata"] || {};
    __snapshots["attachAstSourceMetadata"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("attachAstSourceMetadata [determinism] argset_2", () => {
  const __args = ["seed_value", ""];
  const first = __attempt("attachAstSourceMetadata", __args);
  const second = __attempt("attachAstSourceMetadata", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("attachAstSourceMetadata [immutability] argset_2", () => {
  const __args = ["seed_value", ""];
  const before = JSON.stringify(__args);
  const result = __attempt("attachAstSourceMetadata", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("attachAstSourceMetadata [snapshot] argset_2", () => {
  const __args = ["seed_value", ""];
  const actual = JSON.stringify(__attempt("attachAstSourceMetadata", __args));
  const stored = __snapshots["attachAstSourceMetadata"] && __snapshots["attachAstSourceMetadata"][8];
  if (__capture || stored === undefined) {
    __snapshots["attachAstSourceMetadata"] = __snapshots["attachAstSourceMetadata"] || {};
    __snapshots["attachAstSourceMetadata"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("attachAstSourceMetadata [determinism] argset_3", () => {
  const __args = ["seed_value", "  spaced  "];
  const first = __attempt("attachAstSourceMetadata", __args);
  const second = __attempt("attachAstSourceMetadata", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("attachAstSourceMetadata [immutability] argset_3", () => {
  const __args = ["seed_value", "  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("attachAstSourceMetadata", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("attachAstSourceMetadata [snapshot] argset_3", () => {
  const __args = ["seed_value", "  spaced  "];
  const actual = JSON.stringify(__attempt("attachAstSourceMetadata", __args));
  const stored = __snapshots["attachAstSourceMetadata"] && __snapshots["attachAstSourceMetadata"][11];
  if (__capture || stored === undefined) {
    __snapshots["attachAstSourceMetadata"] = __snapshots["attachAstSourceMetadata"] || {};
    __snapshots["attachAstSourceMetadata"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("attachAstSourceMetadata [determinism] argset_4", () => {
  const __args = ["seed_value", "Alpha42"];
  const first = __attempt("attachAstSourceMetadata", __args);
  const second = __attempt("attachAstSourceMetadata", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("attachAstSourceMetadata [immutability] argset_4", () => {
  const __args = ["seed_value", "Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("attachAstSourceMetadata", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("attachAstSourceMetadata [snapshot] argset_4", () => {
  const __args = ["seed_value", "Alpha42"];
  const actual = JSON.stringify(__attempt("attachAstSourceMetadata", __args));
  const stored = __snapshots["attachAstSourceMetadata"] && __snapshots["attachAstSourceMetadata"][14];
  if (__capture || stored === undefined) {
    __snapshots["attachAstSourceMetadata"] = __snapshots["attachAstSourceMetadata"] || {};
    __snapshots["attachAstSourceMetadata"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("attachAstSourceMetadata [determinism] argset_5", () => {
  const __args = ["seed_value", ""];
  const first = __attempt("attachAstSourceMetadata", __args);
  const second = __attempt("attachAstSourceMetadata", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("attachAstSourceMetadata [immutability] argset_5", () => {
  const __args = ["seed_value", ""];
  const before = JSON.stringify(__args);
  const result = __attempt("attachAstSourceMetadata", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("attachAstSourceMetadata [snapshot] argset_5", () => {
  const __args = ["seed_value", ""];
  const actual = JSON.stringify(__attempt("attachAstSourceMetadata", __args));
  const stored = __snapshots["attachAstSourceMetadata"] && __snapshots["attachAstSourceMetadata"][17];
  if (__capture || stored === undefined) {
    __snapshots["attachAstSourceMetadata"] = __snapshots["attachAstSourceMetadata"] || {};
    __snapshots["attachAstSourceMetadata"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("attachAstSourceMetadata [edge_safety] edge_0", () => {
  const __args = [null, ""];
  try {
    __call("attachAstSourceMetadata", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("attachAstSourceMetadata [edge_safety] edge_1", () => {
  const __args = [undefined, ""];
  try {
    __call("attachAstSourceMetadata", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("attachAstSourceMetadata [edge_safety] edge_2", () => {
  const __args = ["seed_value", ""];
  try {
    __call("attachAstSourceMetadata", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("attachAstSourceMetadata [edge_safety] edge_3", () => {
  const __args = ["seed_value", " "];
  try {
    __call("attachAstSourceMetadata", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("attachAstSourceMetadata [edge_safety] edge_4", () => {
  const __args = ["seed_value", "\t"];
  try {
    __call("attachAstSourceMetadata", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("attachAstSourceMetadata [edge_safety] edge_5", () => {
  const __args = ["seed_value", "0"];
  try {
    __call("attachAstSourceMetadata", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("attachAstSourceMetadata [edge_safety] edge_6", () => {
  const __args = ["seed_value", "null"];
  try {
    __call("attachAstSourceMetadata", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("generateTraceId [edge_safety] edge_0", () => {
  const __args = [];
  try {
    __call("generateTraceId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryRollback [determinism] argset_0", () => {
  const __args = ["seed_value", [], {}];
  const first = __attempt("tryRollback", __args);
  const second = __attempt("tryRollback", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryRollback [immutability] argset_0", () => {
  const __args = ["seed_value", [], {}];
  const before = JSON.stringify(__args);
  const result = __attempt("tryRollback", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryRollback [snapshot] argset_0", () => {
  const __args = ["seed_value", [], {}];
  const actual = JSON.stringify(__attempt("tryRollback", __args));
  const stored = __snapshots["tryRollback"] && __snapshots["tryRollback"][2];
  if (__capture || stored === undefined) {
    __snapshots["tryRollback"] = __snapshots["tryRollback"] || {};
    __snapshots["tryRollback"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("tryRollback [determinism] argset_1", () => {
  const __args = ["seed_value", [3, 1, 2], {"a": 1}];
  const first = __attempt("tryRollback", __args);
  const second = __attempt("tryRollback", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryRollback [immutability] argset_1", () => {
  const __args = ["seed_value", [3, 1, 2], {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("tryRollback", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryRollback [snapshot] argset_1", () => {
  const __args = ["seed_value", [3, 1, 2], {"a": 1}];
  const actual = JSON.stringify(__attempt("tryRollback", __args));
  const stored = __snapshots["tryRollback"] && __snapshots["tryRollback"][5];
  if (__capture || stored === undefined) {
    __snapshots["tryRollback"] = __snapshots["tryRollback"] || {};
    __snapshots["tryRollback"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("tryRollback [determinism] argset_2", () => {
  const __args = ["seed_value", [0], {}];
  const first = __attempt("tryRollback", __args);
  const second = __attempt("tryRollback", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryRollback [immutability] argset_2", () => {
  const __args = ["seed_value", [0], {}];
  const before = JSON.stringify(__args);
  const result = __attempt("tryRollback", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryRollback [snapshot] argset_2", () => {
  const __args = ["seed_value", [0], {}];
  const actual = JSON.stringify(__attempt("tryRollback", __args));
  const stored = __snapshots["tryRollback"] && __snapshots["tryRollback"][8];
  if (__capture || stored === undefined) {
    __snapshots["tryRollback"] = __snapshots["tryRollback"] || {};
    __snapshots["tryRollback"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("tryRollback [determinism] argset_3", () => {
  const __args = ["seed_value", [3, 1, 2], {"a": 1}];
  const first = __attempt("tryRollback", __args);
  const second = __attempt("tryRollback", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryRollback [immutability] argset_3", () => {
  const __args = ["seed_value", [3, 1, 2], {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("tryRollback", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryRollback [snapshot] argset_3", () => {
  const __args = ["seed_value", [3, 1, 2], {"a": 1}];
  const actual = JSON.stringify(__attempt("tryRollback", __args));
  const stored = __snapshots["tryRollback"] && __snapshots["tryRollback"][11];
  if (__capture || stored === undefined) {
    __snapshots["tryRollback"] = __snapshots["tryRollback"] || {};
    __snapshots["tryRollback"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("tryRollback [edge_safety] edge_0", () => {
  const __args = [null, [], {}];
  try {
    __call("tryRollback", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryRollback [edge_safety] edge_1", () => {
  const __args = [null, [3, 1, 2], {"a": 1}];
  try {
    __call("tryRollback", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryRollback [edge_safety] edge_2", () => {
  const __args = [undefined, [3, 1, 2], {"a": 1}];
  try {
    __call("tryRollback", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryRollback [edge_safety] edge_3", () => {
  const __args = ["seed_value", [], {"a": 1}];
  try {
    __call("tryRollback", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryRollback [edge_safety] edge_4", () => {
  const __args = ["seed_value", [null], {"a": 1}];
  try {
    __call("tryRollback", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryRollback [edge_safety] edge_5", () => {
  const __args = ["seed_value", [3, 1, 2], {}];
  try {
    __call("tryRollback", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryRollback [edge_safety] edge_6", () => {
  const __args = ["seed_value", [3, 1, 2], null];
  try {
    __call("tryRollback", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

