// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_intent_dispatcher_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\plugins\\code_shared_intent_dispatcher_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/plugins__code_shared_intent_dispatcher_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("run_intent [determinism] argset_0", () => {
  const __args = ["seed_value", "alpha", {}];
  const first = __attempt("run_intent", __args);
  const second = __attempt("run_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("run_intent [immutability] argset_0", () => {
  const __args = ["seed_value", "alpha", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("run_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("run_intent [determinism] argset_1", () => {
  const __args = ["seed_value", "hello world", {"a": 1}];
  const first = __attempt("run_intent", __args);
  const second = __attempt("run_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("run_intent [immutability] argset_1", () => {
  const __args = ["seed_value", "hello world", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("run_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("run_intent [determinism] argset_2", () => {
  const __args = ["seed_value", "", {}];
  const first = __attempt("run_intent", __args);
  const second = __attempt("run_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("run_intent [immutability] argset_2", () => {
  const __args = ["seed_value", "", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("run_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("run_intent [determinism] argset_3", () => {
  const __args = ["seed_value", "  spaced  ", {"a": 1}];
  const first = __attempt("run_intent", __args);
  const second = __attempt("run_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("run_intent [immutability] argset_3", () => {
  const __args = ["seed_value", "  spaced  ", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("run_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("run_intent [determinism] argset_4", () => {
  const __args = ["seed_value", "Alpha42", {}];
  const first = __attempt("run_intent", __args);
  const second = __attempt("run_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("run_intent [immutability] argset_4", () => {
  const __args = ["seed_value", "Alpha42", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("run_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("run_intent [determinism] argset_5", () => {
  const __args = ["seed_value", "", {"a": 1}];
  const first = __attempt("run_intent", __args);
  const second = __attempt("run_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("run_intent [immutability] argset_5", () => {
  const __args = ["seed_value", "", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("run_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("run_intent [edge_safety] edge_0", () => {
  const __args = [null, "", {}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_1", () => {
  const __args = [null, "", {"a": 1}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_2", () => {
  const __args = [undefined, "", {"a": 1}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_3", () => {
  const __args = ["seed_value", "", {"a": 1}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_4", () => {
  const __args = ["seed_value", " ", {"a": 1}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_5", () => {
  const __args = ["seed_value", "\t", {"a": 1}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_6", () => {
  const __args = ["seed_value", "0", {"a": 1}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_7", () => {
  const __args = ["seed_value", "null", {"a": 1}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_8", () => {
  const __args = ["seed_value", "", {}];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("run_intent [edge_safety] edge_9", () => {
  const __args = ["seed_value", "", null];
  try {
    __call("run_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("register_intent [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("register_intent", __args);
  const second = __attempt("register_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("register_intent [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("register_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("register_intent [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("register_intent", __args);
  const second = __attempt("register_intent", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("register_intent [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("register_intent", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("register_intent [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("register_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("register_intent [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("register_intent", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

