// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_sorting_v2_2_0_draft.js
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_sorting_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/sorting_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const instance = new mod();
function __call(name, args) {
  if (typeof instance[name] !== "function") throw new Error("missing method " + name);
  return instance[name].apply(instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("execute [determinism] argset_0", () => {
  const __args = [[], "seed_value"];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_0", () => {
  const __args = [[], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_0", () => {
  const __args = [[], "seed_value"];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][2];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("execute [determinism] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][5];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("execute [determinism] argset_2", () => {
  const __args = [[0], "seed_value"];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_2", () => {
  const __args = [[0], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_2", () => {
  const __args = [[0], "seed_value"];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][8];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("execute [determinism] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][11];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("execute [edge_safety] edge_0", () => {
  const __args = [[], null];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_1", () => {
  const __args = [[], "seed_value"];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_2", () => {
  const __args = [[null], "seed_value"];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], null];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], undefined];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [determinism] argset_0", () => {
  const __args = [[], "alpha", "seed_value"];
  const first = __attempt("sortByKey", __args);
  const second = __attempt("sortByKey", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("sortByKey [immutability] argset_0", () => {
  const __args = [[], "alpha", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("sortByKey", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("sortByKey [snapshot] argset_0", () => {
  const __args = [[], "alpha", "seed_value"];
  const actual = JSON.stringify(__attempt("sortByKey", __args));
  const stored = __snapshots["sortByKey"] && __snapshots["sortByKey"][2];
  if (__capture || stored === undefined) {
    __snapshots["sortByKey"] = __snapshots["sortByKey"] || {};
    __snapshots["sortByKey"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("sortByKey [determinism] argset_1", () => {
  const __args = [[3, 1, 2], "hello world", "seed_value"];
  const first = __attempt("sortByKey", __args);
  const second = __attempt("sortByKey", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("sortByKey [immutability] argset_1", () => {
  const __args = [[3, 1, 2], "hello world", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("sortByKey", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("sortByKey [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], "hello world", "seed_value"];
  const actual = JSON.stringify(__attempt("sortByKey", __args));
  const stored = __snapshots["sortByKey"] && __snapshots["sortByKey"][5];
  if (__capture || stored === undefined) {
    __snapshots["sortByKey"] = __snapshots["sortByKey"] || {};
    __snapshots["sortByKey"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("sortByKey [determinism] argset_2", () => {
  const __args = [[0], "", "seed_value"];
  const first = __attempt("sortByKey", __args);
  const second = __attempt("sortByKey", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("sortByKey [immutability] argset_2", () => {
  const __args = [[0], "", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("sortByKey", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("sortByKey [snapshot] argset_2", () => {
  const __args = [[0], "", "seed_value"];
  const actual = JSON.stringify(__attempt("sortByKey", __args));
  const stored = __snapshots["sortByKey"] && __snapshots["sortByKey"][8];
  if (__capture || stored === undefined) {
    __snapshots["sortByKey"] = __snapshots["sortByKey"] || {};
    __snapshots["sortByKey"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("sortByKey [determinism] argset_3", () => {
  const __args = [[], "  spaced  ", "seed_value"];
  const first = __attempt("sortByKey", __args);
  const second = __attempt("sortByKey", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("sortByKey [immutability] argset_3", () => {
  const __args = [[], "  spaced  ", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("sortByKey", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("sortByKey [snapshot] argset_3", () => {
  const __args = [[], "  spaced  ", "seed_value"];
  const actual = JSON.stringify(__attempt("sortByKey", __args));
  const stored = __snapshots["sortByKey"] && __snapshots["sortByKey"][11];
  if (__capture || stored === undefined) {
    __snapshots["sortByKey"] = __snapshots["sortByKey"] || {};
    __snapshots["sortByKey"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("sortByKey [determinism] argset_4", () => {
  const __args = [[3, 1, 2], "Alpha42", "seed_value"];
  const first = __attempt("sortByKey", __args);
  const second = __attempt("sortByKey", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("sortByKey [immutability] argset_4", () => {
  const __args = [[3, 1, 2], "Alpha42", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("sortByKey", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("sortByKey [snapshot] argset_4", () => {
  const __args = [[3, 1, 2], "Alpha42", "seed_value"];
  const actual = JSON.stringify(__attempt("sortByKey", __args));
  const stored = __snapshots["sortByKey"] && __snapshots["sortByKey"][14];
  if (__capture || stored === undefined) {
    __snapshots["sortByKey"] = __snapshots["sortByKey"] || {};
    __snapshots["sortByKey"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("sortByKey [determinism] argset_5", () => {
  const __args = [[3, 1, 2], "", "seed_value"];
  const first = __attempt("sortByKey", __args);
  const second = __attempt("sortByKey", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("sortByKey [immutability] argset_5", () => {
  const __args = [[3, 1, 2], "", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("sortByKey", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("sortByKey [snapshot] argset_5", () => {
  const __args = [[3, 1, 2], "", "seed_value"];
  const actual = JSON.stringify(__attempt("sortByKey", __args));
  const stored = __snapshots["sortByKey"] && __snapshots["sortByKey"][17];
  if (__capture || stored === undefined) {
    __snapshots["sortByKey"] = __snapshots["sortByKey"] || {};
    __snapshots["sortByKey"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("sortByKey [edge_safety] edge_0", () => {
  const __args = [[], "", null];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_1", () => {
  const __args = [[], "", "seed_value"];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_2", () => {
  const __args = [[null], "", "seed_value"];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], "", "seed_value"];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], " ", "seed_value"];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_5", () => {
  const __args = [[3, 1, 2], "\t", "seed_value"];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_6", () => {
  const __args = [[3, 1, 2], "0", "seed_value"];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_7", () => {
  const __args = [[3, 1, 2], "null", "seed_value"];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_8", () => {
  const __args = [[3, 1, 2], "", null];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("sortByKey [edge_safety] edge_9", () => {
  const __args = [[3, 1, 2], "", undefined];
  try {
    __call("sortByKey", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

