// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_text_v2_2_0_draft.js
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_text_v2_2_0_draft.js");
const SNAPSHOT_PATH = path.resolve(__dirname, "snapshots/text_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("escape_text [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("escape_text", __args);
  const second = __attempt("escape_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("escape_text [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("escape_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("escape_text [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("escape_text", __args));
  const stored = __snapshots["escape_text"] && __snapshots["escape_text"][2];
  if (__capture || stored === undefined) {
    __snapshots["escape_text"] = __snapshots["escape_text"] || {};
    __snapshots["escape_text"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("escape_text [edge_safety] argset_0", () => {
  const __args = ["alpha"];
  try {
    __call("escape_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("escape_text [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("escape_text", __args);
  const second = __attempt("escape_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("escape_text [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("escape_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("escape_text [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("escape_text", __args));
  const stored = __snapshots["escape_text"] && __snapshots["escape_text"][6];
  if (__capture || stored === undefined) {
    __snapshots["escape_text"] = __snapshots["escape_text"] || {};
    __snapshots["escape_text"][6] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 6");
  }
});

test("escape_text [edge_safety] argset_1", () => {
  const __args = ["hello world"];
  try {
    __call("escape_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("escape_text [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("escape_text", __args);
  const second = __attempt("escape_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("escape_text [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("escape_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("escape_text [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("escape_text", __args));
  const stored = __snapshots["escape_text"] && __snapshots["escape_text"][10];
  if (__capture || stored === undefined) {
    __snapshots["escape_text"] = __snapshots["escape_text"] || {};
    __snapshots["escape_text"][10] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 10");
  }
});

test("escape_text [edge_safety] argset_2", () => {
  const __args = [""];
  try {
    __call("escape_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("escape_text [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("escape_text", __args);
  const second = __attempt("escape_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("escape_text [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("escape_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("escape_text [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("escape_text", __args));
  const stored = __snapshots["escape_text"] && __snapshots["escape_text"][14];
  if (__capture || stored === undefined) {
    __snapshots["escape_text"] = __snapshots["escape_text"] || {};
    __snapshots["escape_text"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("escape_text [edge_safety] argset_3", () => {
  const __args = ["  spaced  "];
  try {
    __call("escape_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("escape_text [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("escape_text", __args);
  const second = __attempt("escape_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("escape_text [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("escape_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("escape_text [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("escape_text", __args));
  const stored = __snapshots["escape_text"] && __snapshots["escape_text"][18];
  if (__capture || stored === undefined) {
    __snapshots["escape_text"] = __snapshots["escape_text"] || {};
    __snapshots["escape_text"][18] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 18");
  }
});

test("escape_text [edge_safety] argset_4", () => {
  const __args = ["Alpha42"];
  try {
    __call("escape_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("escape_text [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("escape_text", __args);
  const second = __attempt("escape_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("escape_text [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("escape_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("escape_text [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("escape_text", __args));
  const stored = __snapshots["escape_text"] && __snapshots["escape_text"][22];
  if (__capture || stored === undefined) {
    __snapshots["escape_text"] = __snapshots["escape_text"] || {};
    __snapshots["escape_text"][22] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 22");
  }
});

test("escape_text [edge_safety] argset_5", () => {
  const __args = [""];
  try {
    __call("escape_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("escape_text [determinism] argset_6", () => {
  const __args = ["alpha"];
  const first = __attempt("escape_text", __args);
  const second = __attempt("escape_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("escape_text [immutability] argset_6", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("escape_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("escape_text [snapshot] argset_6", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("escape_text", __args));
  const stored = __snapshots["escape_text"] && __snapshots["escape_text"][26];
  if (__capture || stored === undefined) {
    __snapshots["escape_text"] = __snapshots["escape_text"] || {};
    __snapshots["escape_text"][26] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 26");
  }
});

test("escape_text [edge_safety] argset_6", () => {
  const __args = ["alpha"];
  try {
    __call("escape_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("join_mapped [determinism] argset_0", () => {
  const __args = [[], (function stub(value) { return value; })];
  const first = __attempt("join_mapped", __args);
  const second = __attempt("join_mapped", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("join_mapped [immutability] argset_0", () => {
  const __args = [[], (function stub(value) { return value; })];
  const before = JSON.stringify(__args);
  const result = __attempt("join_mapped", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("join_mapped [snapshot] argset_0", () => {
  const __args = [[], (function stub(value) { return value; })];
  const actual = JSON.stringify(__attempt("join_mapped", __args));
  const stored = __snapshots["join_mapped"] && __snapshots["join_mapped"][2];
  if (__capture || stored === undefined) {
    __snapshots["join_mapped"] = __snapshots["join_mapped"] || {};
    __snapshots["join_mapped"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("join_mapped [edge_safety] argset_0", () => {
  const __args = [[], (function stub(value) { return value; })];
  try {
    __call("join_mapped", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("join_mapped [determinism] argset_1", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  const first = __attempt("join_mapped", __args);
  const second = __attempt("join_mapped", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("join_mapped [immutability] argset_1", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  const before = JSON.stringify(__args);
  const result = __attempt("join_mapped", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("join_mapped [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  const actual = JSON.stringify(__attempt("join_mapped", __args));
  const stored = __snapshots["join_mapped"] && __snapshots["join_mapped"][6];
  if (__capture || stored === undefined) {
    __snapshots["join_mapped"] = __snapshots["join_mapped"] || {};
    __snapshots["join_mapped"][6] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 6");
  }
});

test("join_mapped [edge_safety] argset_1", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  try {
    __call("join_mapped", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("join_mapped [determinism] argset_2", () => {
  const __args = [[0], (function stub(value) { return value; })];
  const first = __attempt("join_mapped", __args);
  const second = __attempt("join_mapped", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("join_mapped [immutability] argset_2", () => {
  const __args = [[0], (function stub(value) { return value; })];
  const before = JSON.stringify(__args);
  const result = __attempt("join_mapped", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("join_mapped [snapshot] argset_2", () => {
  const __args = [[0], (function stub(value) { return value; })];
  const actual = JSON.stringify(__attempt("join_mapped", __args));
  const stored = __snapshots["join_mapped"] && __snapshots["join_mapped"][10];
  if (__capture || stored === undefined) {
    __snapshots["join_mapped"] = __snapshots["join_mapped"] || {};
    __snapshots["join_mapped"][10] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 10");
  }
});

test("join_mapped [edge_safety] argset_2", () => {
  const __args = [[0], (function stub(value) { return value; })];
  try {
    __call("join_mapped", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("join_mapped [determinism] argset_3", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  const first = __attempt("join_mapped", __args);
  const second = __attempt("join_mapped", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("join_mapped [immutability] argset_3", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  const before = JSON.stringify(__args);
  const result = __attempt("join_mapped", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("join_mapped [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  const actual = JSON.stringify(__attempt("join_mapped", __args));
  const stored = __snapshots["join_mapped"] && __snapshots["join_mapped"][14];
  if (__capture || stored === undefined) {
    __snapshots["join_mapped"] = __snapshots["join_mapped"] || {};
    __snapshots["join_mapped"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("join_mapped [edge_safety] argset_3", () => {
  const __args = [[3, 1, 2], (function stub(value) { return value; })];
  try {
    __call("join_mapped", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("join_mapped [determinism] argset_4", () => {
  const __args = [[], (function stub(value) { return value; })];
  const first = __attempt("join_mapped", __args);
  const second = __attempt("join_mapped", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("join_mapped [immutability] argset_4", () => {
  const __args = [[], (function stub(value) { return value; })];
  const before = JSON.stringify(__args);
  const result = __attempt("join_mapped", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("join_mapped [snapshot] argset_4", () => {
  const __args = [[], (function stub(value) { return value; })];
  const actual = JSON.stringify(__attempt("join_mapped", __args));
  const stored = __snapshots["join_mapped"] && __snapshots["join_mapped"][18];
  if (__capture || stored === undefined) {
    __snapshots["join_mapped"] = __snapshots["join_mapped"] || {};
    __snapshots["join_mapped"][18] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 18");
  }
});

test("join_mapped [edge_safety] argset_4", () => {
  const __args = [[], (function stub(value) { return value; })];
  try {
    __call("join_mapped", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][2];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("tokenize [edge_safety] argset_0", () => {
  const __args = ["alpha"];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][6];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][6] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 6");
  }
});

test("tokenize [edge_safety] argset_1", () => {
  const __args = ["hello world"];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][10];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][10] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 10");
  }
});

test("tokenize [edge_safety] argset_2", () => {
  const __args = [""];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][14];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("tokenize [edge_safety] argset_3", () => {
  const __args = ["  spaced  "];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][18];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][18] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 18");
  }
});

test("tokenize [edge_safety] argset_4", () => {
  const __args = ["Alpha42"];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][22];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][22] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 22");
  }
});

test("tokenize [edge_safety] argset_5", () => {
  const __args = [""];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_6", () => {
  const __args = ["alpha"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_6", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_6", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][26];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][26] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 26");
  }
});

test("tokenize [edge_safety] argset_6", () => {
  const __args = ["alpha"];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalize_spaces [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("normalize_spaces", __args);
  const second = __attempt("normalize_spaces", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalize_spaces [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("normalize_spaces", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalize_spaces [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("normalize_spaces", __args));
  const stored = __snapshots["normalize_spaces"] && __snapshots["normalize_spaces"][2];
  if (__capture || stored === undefined) {
    __snapshots["normalize_spaces"] = __snapshots["normalize_spaces"] || {};
    __snapshots["normalize_spaces"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("normalize_spaces [edge_safety] argset_0", () => {
  const __args = ["alpha"];
  try {
    __call("normalize_spaces", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalize_spaces [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("normalize_spaces", __args);
  const second = __attempt("normalize_spaces", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalize_spaces [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("normalize_spaces", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalize_spaces [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("normalize_spaces", __args));
  const stored = __snapshots["normalize_spaces"] && __snapshots["normalize_spaces"][6];
  if (__capture || stored === undefined) {
    __snapshots["normalize_spaces"] = __snapshots["normalize_spaces"] || {};
    __snapshots["normalize_spaces"][6] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 6");
  }
});

test("normalize_spaces [edge_safety] argset_1", () => {
  const __args = ["hello world"];
  try {
    __call("normalize_spaces", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalize_spaces [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("normalize_spaces", __args);
  const second = __attempt("normalize_spaces", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalize_spaces [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("normalize_spaces", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalize_spaces [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("normalize_spaces", __args));
  const stored = __snapshots["normalize_spaces"] && __snapshots["normalize_spaces"][10];
  if (__capture || stored === undefined) {
    __snapshots["normalize_spaces"] = __snapshots["normalize_spaces"] || {};
    __snapshots["normalize_spaces"][10] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 10");
  }
});

test("normalize_spaces [edge_safety] argset_2", () => {
  const __args = [""];
  try {
    __call("normalize_spaces", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalize_spaces [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("normalize_spaces", __args);
  const second = __attempt("normalize_spaces", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalize_spaces [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("normalize_spaces", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalize_spaces [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("normalize_spaces", __args));
  const stored = __snapshots["normalize_spaces"] && __snapshots["normalize_spaces"][14];
  if (__capture || stored === undefined) {
    __snapshots["normalize_spaces"] = __snapshots["normalize_spaces"] || {};
    __snapshots["normalize_spaces"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("normalize_spaces [edge_safety] argset_3", () => {
  const __args = ["  spaced  "];
  try {
    __call("normalize_spaces", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalize_spaces [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("normalize_spaces", __args);
  const second = __attempt("normalize_spaces", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalize_spaces [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("normalize_spaces", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalize_spaces [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("normalize_spaces", __args));
  const stored = __snapshots["normalize_spaces"] && __snapshots["normalize_spaces"][18];
  if (__capture || stored === undefined) {
    __snapshots["normalize_spaces"] = __snapshots["normalize_spaces"] || {};
    __snapshots["normalize_spaces"][18] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 18");
  }
});

test("normalize_spaces [edge_safety] argset_4", () => {
  const __args = ["Alpha42"];
  try {
    __call("normalize_spaces", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalize_spaces [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("normalize_spaces", __args);
  const second = __attempt("normalize_spaces", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalize_spaces [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("normalize_spaces", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalize_spaces [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("normalize_spaces", __args));
  const stored = __snapshots["normalize_spaces"] && __snapshots["normalize_spaces"][22];
  if (__capture || stored === undefined) {
    __snapshots["normalize_spaces"] = __snapshots["normalize_spaces"] || {};
    __snapshots["normalize_spaces"][22] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 22");
  }
});

test("normalize_spaces [edge_safety] argset_5", () => {
  const __args = [""];
  try {
    __call("normalize_spaces", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalize_spaces [determinism] argset_6", () => {
  const __args = ["alpha"];
  const first = __attempt("normalize_spaces", __args);
  const second = __attempt("normalize_spaces", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalize_spaces [immutability] argset_6", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("normalize_spaces", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalize_spaces [snapshot] argset_6", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("normalize_spaces", __args));
  const stored = __snapshots["normalize_spaces"] && __snapshots["normalize_spaces"][26];
  if (__capture || stored === undefined) {
    __snapshots["normalize_spaces"] = __snapshots["normalize_spaces"] || {};
    __snapshots["normalize_spaces"][26] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 26");
  }
});

test("normalize_spaces [edge_safety] argset_6", () => {
  const __args = ["alpha"];
  try {
    __call("normalize_spaces", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

