// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_standard_deviation_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_standard_deviation_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_standard_deviation_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("execute [determinism] argset_0", () => {
  const __args = [[]];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_0", () => {
  const __args = [[]];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [determinism] argset_1", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_1", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [determinism] argset_2", () => {
  const __args = [[0]];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_2", () => {
  const __args = [[0]];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [determinism] argset_3", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_3", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [edge_safety] edge_0", () => {
  const __args = [[]];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_1", () => {
  const __args = [[null]];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

