// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_compiler_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_compiler_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_compiler_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("compile [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("compile", __args);
  const second = __attempt("compile", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("compile [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("compile", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("compile [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("compile", __args));
  const stored = __snapshots["compile"] && __snapshots["compile"][2];
  if (__capture || stored === undefined) {
    __snapshots["compile"] = __snapshots["compile"] || {};
    __snapshots["compile"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("compile [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("compile", __args);
  const second = __attempt("compile", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("compile [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("compile", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("compile [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("compile", __args));
  const stored = __snapshots["compile"] && __snapshots["compile"][5];
  if (__capture || stored === undefined) {
    __snapshots["compile"] = __snapshots["compile"] || {};
    __snapshots["compile"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("compile [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("compile", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("compile [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("compile", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveAction [determinism] argset_0", () => {
  const __args = ["seed_value", "seed_value"];
  const first = __attempt("resolveAction", __args);
  const second = __attempt("resolveAction", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveAction [immutability] argset_0", () => {
  const __args = ["seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveAction", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveAction [snapshot] argset_0", () => {
  const __args = ["seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("resolveAction", __args));
  const stored = __snapshots["resolveAction"] && __snapshots["resolveAction"][2];
  if (__capture || stored === undefined) {
    __snapshots["resolveAction"] = __snapshots["resolveAction"] || {};
    __snapshots["resolveAction"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("resolveAction [determinism] argset_1", () => {
  const __args = ["seed_value", "seed_value"];
  const first = __attempt("resolveAction", __args);
  const second = __attempt("resolveAction", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolveAction [immutability] argset_1", () => {
  const __args = ["seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("resolveAction", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolveAction [snapshot] argset_1", () => {
  const __args = ["seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("resolveAction", __args));
  const stored = __snapshots["resolveAction"] && __snapshots["resolveAction"][5];
  if (__capture || stored === undefined) {
    __snapshots["resolveAction"] = __snapshots["resolveAction"] || {};
    __snapshots["resolveAction"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("resolveAction [edge_safety] edge_0", () => {
  const __args = [null, null];
  try {
    __call("resolveAction", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveAction [edge_safety] edge_1", () => {
  const __args = [null, "seed_value"];
  try {
    __call("resolveAction", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveAction [edge_safety] edge_2", () => {
  const __args = [undefined, "seed_value"];
  try {
    __call("resolveAction", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveAction [edge_safety] edge_3", () => {
  const __args = ["seed_value", null];
  try {
    __call("resolveAction", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolveAction [edge_safety] edge_4", () => {
  const __args = ["seed_value", undefined];
  try {
    __call("resolveAction", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [determinism] argset_0", () => {
  const __args = [{}, "seed_value", "alpha"];
  const first = __attempt("deepReplace", __args);
  const second = __attempt("deepReplace", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deepReplace [immutability] argset_0", () => {
  const __args = [{}, "seed_value", "alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("deepReplace", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deepReplace [snapshot] argset_0", () => {
  const __args = [{}, "seed_value", "alpha"];
  const actual = JSON.stringify(__attempt("deepReplace", __args));
  const stored = __snapshots["deepReplace"] && __snapshots["deepReplace"][2];
  if (__capture || stored === undefined) {
    __snapshots["deepReplace"] = __snapshots["deepReplace"] || {};
    __snapshots["deepReplace"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("deepReplace [determinism] argset_1", () => {
  const __args = [{"a": 1}, "seed_value", "hello world"];
  const first = __attempt("deepReplace", __args);
  const second = __attempt("deepReplace", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deepReplace [immutability] argset_1", () => {
  const __args = [{"a": 1}, "seed_value", "hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("deepReplace", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deepReplace [snapshot] argset_1", () => {
  const __args = [{"a": 1}, "seed_value", "hello world"];
  const actual = JSON.stringify(__attempt("deepReplace", __args));
  const stored = __snapshots["deepReplace"] && __snapshots["deepReplace"][5];
  if (__capture || stored === undefined) {
    __snapshots["deepReplace"] = __snapshots["deepReplace"] || {};
    __snapshots["deepReplace"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("deepReplace [determinism] argset_2", () => {
  const __args = [{}, "seed_value", ""];
  const first = __attempt("deepReplace", __args);
  const second = __attempt("deepReplace", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deepReplace [immutability] argset_2", () => {
  const __args = [{}, "seed_value", ""];
  const before = JSON.stringify(__args);
  const result = __attempt("deepReplace", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deepReplace [snapshot] argset_2", () => {
  const __args = [{}, "seed_value", ""];
  const actual = JSON.stringify(__attempt("deepReplace", __args));
  const stored = __snapshots["deepReplace"] && __snapshots["deepReplace"][8];
  if (__capture || stored === undefined) {
    __snapshots["deepReplace"] = __snapshots["deepReplace"] || {};
    __snapshots["deepReplace"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("deepReplace [determinism] argset_3", () => {
  const __args = [{"a": 1}, "seed_value", "  spaced  "];
  const first = __attempt("deepReplace", __args);
  const second = __attempt("deepReplace", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deepReplace [immutability] argset_3", () => {
  const __args = [{"a": 1}, "seed_value", "  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("deepReplace", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deepReplace [snapshot] argset_3", () => {
  const __args = [{"a": 1}, "seed_value", "  spaced  "];
  const actual = JSON.stringify(__attempt("deepReplace", __args));
  const stored = __snapshots["deepReplace"] && __snapshots["deepReplace"][11];
  if (__capture || stored === undefined) {
    __snapshots["deepReplace"] = __snapshots["deepReplace"] || {};
    __snapshots["deepReplace"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("deepReplace [determinism] argset_4", () => {
  const __args = [{}, "seed_value", "Alpha42"];
  const first = __attempt("deepReplace", __args);
  const second = __attempt("deepReplace", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deepReplace [immutability] argset_4", () => {
  const __args = [{}, "seed_value", "Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("deepReplace", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deepReplace [snapshot] argset_4", () => {
  const __args = [{}, "seed_value", "Alpha42"];
  const actual = JSON.stringify(__attempt("deepReplace", __args));
  const stored = __snapshots["deepReplace"] && __snapshots["deepReplace"][14];
  if (__capture || stored === undefined) {
    __snapshots["deepReplace"] = __snapshots["deepReplace"] || {};
    __snapshots["deepReplace"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("deepReplace [determinism] argset_5", () => {
  const __args = [{"a": 1}, "seed_value", ""];
  const first = __attempt("deepReplace", __args);
  const second = __attempt("deepReplace", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("deepReplace [immutability] argset_5", () => {
  const __args = [{"a": 1}, "seed_value", ""];
  const before = JSON.stringify(__args);
  const result = __attempt("deepReplace", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("deepReplace [snapshot] argset_5", () => {
  const __args = [{"a": 1}, "seed_value", ""];
  const actual = JSON.stringify(__attempt("deepReplace", __args));
  const stored = __snapshots["deepReplace"] && __snapshots["deepReplace"][17];
  if (__capture || stored === undefined) {
    __snapshots["deepReplace"] = __snapshots["deepReplace"] || {};
    __snapshots["deepReplace"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("deepReplace [edge_safety] edge_0", () => {
  const __args = [{}, null, ""];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_1", () => {
  const __args = [{}, "seed_value", ""];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_2", () => {
  const __args = [null, "seed_value", ""];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_3", () => {
  const __args = [{"a": 1}, null, ""];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_4", () => {
  const __args = [{"a": 1}, undefined, ""];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_5", () => {
  const __args = [{"a": 1}, "seed_value", ""];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_6", () => {
  const __args = [{"a": 1}, "seed_value", " "];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_7", () => {
  const __args = [{"a": 1}, "seed_value", "\t"];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_8", () => {
  const __args = [{"a": 1}, "seed_value", "0"];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("deepReplace [edge_safety] edge_9", () => {
  const __args = [{"a": 1}, "seed_value", "null"];
  try {
    __call("deepReplace", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

