// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_tokenizer_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_tokenizer_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_tokenizer_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("tokenize [determinism] argset_0", () => {
  const __args = ["alpha", {}];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_0", () => {
  const __args = ["alpha", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_0", () => {
  const __args = ["alpha", {}];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][2];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("tokenize [determinism] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][5];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("tokenize [determinism] argset_2", () => {
  const __args = ["", {}];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_2", () => {
  const __args = ["", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_2", () => {
  const __args = ["", {}];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][8];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("tokenize [determinism] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][11];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("tokenize [determinism] argset_4", () => {
  const __args = ["Alpha42", {}];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_4", () => {
  const __args = ["Alpha42", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_4", () => {
  const __args = ["Alpha42", {}];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][14];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("tokenize [determinism] argset_5", () => {
  const __args = ["", {"a": 1}];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_5", () => {
  const __args = ["", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_5", () => {
  const __args = ["", {"a": 1}];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][17];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("tokenize [edge_safety] edge_0", () => {
  const __args = ["", {}];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_1", () => {
  const __args = ["", {"a": 1}];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_2", () => {
  const __args = [" ", {"a": 1}];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_3", () => {
  const __args = ["\t", {"a": 1}];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_4", () => {
  const __args = ["0", {"a": 1}];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_5", () => {
  const __args = ["null", {"a": 1}];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_6", () => {
  const __args = ["", null];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("scanTokens [determinism] argset_0", () => {
  const __args = ["alpha", {}];
  const first = __attempt("scanTokens", __args);
  const second = __attempt("scanTokens", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("scanTokens [immutability] argset_0", () => {
  const __args = ["alpha", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("scanTokens", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("scanTokens [snapshot] argset_0", () => {
  const __args = ["alpha", {}];
  const actual = JSON.stringify(__attempt("scanTokens", __args));
  const stored = __snapshots["scanTokens"] && __snapshots["scanTokens"][2];
  if (__capture || stored === undefined) {
    __snapshots["scanTokens"] = __snapshots["scanTokens"] || {};
    __snapshots["scanTokens"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("scanTokens [determinism] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const first = __attempt("scanTokens", __args);
  const second = __attempt("scanTokens", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("scanTokens [immutability] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("scanTokens", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("scanTokens [snapshot] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const actual = JSON.stringify(__attempt("scanTokens", __args));
  const stored = __snapshots["scanTokens"] && __snapshots["scanTokens"][5];
  if (__capture || stored === undefined) {
    __snapshots["scanTokens"] = __snapshots["scanTokens"] || {};
    __snapshots["scanTokens"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("scanTokens [determinism] argset_2", () => {
  const __args = ["", {}];
  const first = __attempt("scanTokens", __args);
  const second = __attempt("scanTokens", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("scanTokens [immutability] argset_2", () => {
  const __args = ["", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("scanTokens", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("scanTokens [snapshot] argset_2", () => {
  const __args = ["", {}];
  const actual = JSON.stringify(__attempt("scanTokens", __args));
  const stored = __snapshots["scanTokens"] && __snapshots["scanTokens"][8];
  if (__capture || stored === undefined) {
    __snapshots["scanTokens"] = __snapshots["scanTokens"] || {};
    __snapshots["scanTokens"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("scanTokens [determinism] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const first = __attempt("scanTokens", __args);
  const second = __attempt("scanTokens", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("scanTokens [immutability] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("scanTokens", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("scanTokens [snapshot] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const actual = JSON.stringify(__attempt("scanTokens", __args));
  const stored = __snapshots["scanTokens"] && __snapshots["scanTokens"][11];
  if (__capture || stored === undefined) {
    __snapshots["scanTokens"] = __snapshots["scanTokens"] || {};
    __snapshots["scanTokens"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("scanTokens [determinism] argset_4", () => {
  const __args = ["Alpha42", {}];
  const first = __attempt("scanTokens", __args);
  const second = __attempt("scanTokens", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("scanTokens [immutability] argset_4", () => {
  const __args = ["Alpha42", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("scanTokens", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("scanTokens [snapshot] argset_4", () => {
  const __args = ["Alpha42", {}];
  const actual = JSON.stringify(__attempt("scanTokens", __args));
  const stored = __snapshots["scanTokens"] && __snapshots["scanTokens"][14];
  if (__capture || stored === undefined) {
    __snapshots["scanTokens"] = __snapshots["scanTokens"] || {};
    __snapshots["scanTokens"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("scanTokens [determinism] argset_5", () => {
  const __args = ["", {"a": 1}];
  const first = __attempt("scanTokens", __args);
  const second = __attempt("scanTokens", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("scanTokens [immutability] argset_5", () => {
  const __args = ["", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("scanTokens", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("scanTokens [snapshot] argset_5", () => {
  const __args = ["", {"a": 1}];
  const actual = JSON.stringify(__attempt("scanTokens", __args));
  const stored = __snapshots["scanTokens"] && __snapshots["scanTokens"][17];
  if (__capture || stored === undefined) {
    __snapshots["scanTokens"] = __snapshots["scanTokens"] || {};
    __snapshots["scanTokens"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("scanTokens [edge_safety] edge_0", () => {
  const __args = ["", {}];
  try {
    __call("scanTokens", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("scanTokens [edge_safety] edge_1", () => {
  const __args = ["", {"a": 1}];
  try {
    __call("scanTokens", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("scanTokens [edge_safety] edge_2", () => {
  const __args = [" ", {"a": 1}];
  try {
    __call("scanTokens", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("scanTokens [edge_safety] edge_3", () => {
  const __args = ["\t", {"a": 1}];
  try {
    __call("scanTokens", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("scanTokens [edge_safety] edge_4", () => {
  const __args = ["0", {"a": 1}];
  try {
    __call("scanTokens", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("scanTokens [edge_safety] edge_5", () => {
  const __args = ["null", {"a": 1}];
  try {
    __call("scanTokens", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("scanTokens [edge_safety] edge_6", () => {
  const __args = ["", null];
  try {
    __call("scanTokens", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalizeToken [determinism] argset_0", () => {
  const __args = ["seed_value", {}];
  const first = __attempt("normalizeToken", __args);
  const second = __attempt("normalizeToken", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalizeToken [immutability] argset_0", () => {
  const __args = ["seed_value", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("normalizeToken", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalizeToken [snapshot] argset_0", () => {
  const __args = ["seed_value", {}];
  const actual = JSON.stringify(__attempt("normalizeToken", __args));
  const stored = __snapshots["normalizeToken"] && __snapshots["normalizeToken"][2];
  if (__capture || stored === undefined) {
    __snapshots["normalizeToken"] = __snapshots["normalizeToken"] || {};
    __snapshots["normalizeToken"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("normalizeToken [determinism] argset_1", () => {
  const __args = ["seed_value", {"a": 1}];
  const first = __attempt("normalizeToken", __args);
  const second = __attempt("normalizeToken", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalizeToken [immutability] argset_1", () => {
  const __args = ["seed_value", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("normalizeToken", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalizeToken [snapshot] argset_1", () => {
  const __args = ["seed_value", {"a": 1}];
  const actual = JSON.stringify(__attempt("normalizeToken", __args));
  const stored = __snapshots["normalizeToken"] && __snapshots["normalizeToken"][5];
  if (__capture || stored === undefined) {
    __snapshots["normalizeToken"] = __snapshots["normalizeToken"] || {};
    __snapshots["normalizeToken"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("normalizeToken [determinism] argset_2", () => {
  const __args = ["seed_value", {"a": 1}];
  const first = __attempt("normalizeToken", __args);
  const second = __attempt("normalizeToken", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("normalizeToken [immutability] argset_2", () => {
  const __args = ["seed_value", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("normalizeToken", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("normalizeToken [snapshot] argset_2", () => {
  const __args = ["seed_value", {"a": 1}];
  const actual = JSON.stringify(__attempt("normalizeToken", __args));
  const stored = __snapshots["normalizeToken"] && __snapshots["normalizeToken"][8];
  if (__capture || stored === undefined) {
    __snapshots["normalizeToken"] = __snapshots["normalizeToken"] || {};
    __snapshots["normalizeToken"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("normalizeToken [edge_safety] edge_0", () => {
  const __args = [null, {}];
  try {
    __call("normalizeToken", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalizeToken [edge_safety] edge_1", () => {
  const __args = [null, {"a": 1}];
  try {
    __call("normalizeToken", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalizeToken [edge_safety] edge_2", () => {
  const __args = [undefined, {"a": 1}];
  try {
    __call("normalizeToken", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalizeToken [edge_safety] edge_3", () => {
  const __args = ["seed_value", {}];
  try {
    __call("normalizeToken", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("normalizeToken [edge_safety] edge_4", () => {
  const __args = ["seed_value", null];
  try {
    __call("normalizeToken", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("isQuoted [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("isQuoted", __args);
  const second = __attempt("isQuoted", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("isQuoted [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("isQuoted", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("isQuoted [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("isQuoted", __args));
  const stored = __snapshots["isQuoted"] && __snapshots["isQuoted"][2];
  if (__capture || stored === undefined) {
    __snapshots["isQuoted"] = __snapshots["isQuoted"] || {};
    __snapshots["isQuoted"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("isQuoted [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("isQuoted", __args);
  const second = __attempt("isQuoted", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("isQuoted [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("isQuoted", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("isQuoted [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("isQuoted", __args));
  const stored = __snapshots["isQuoted"] && __snapshots["isQuoted"][5];
  if (__capture || stored === undefined) {
    __snapshots["isQuoted"] = __snapshots["isQuoted"] || {};
    __snapshots["isQuoted"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("isQuoted [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("isQuoted", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("isQuoted [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("isQuoted", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("isPathLike [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("isPathLike", __args);
  const second = __attempt("isPathLike", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("isPathLike [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("isPathLike", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("isPathLike [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("isPathLike", __args));
  const stored = __snapshots["isPathLike"] && __snapshots["isPathLike"][2];
  if (__capture || stored === undefined) {
    __snapshots["isPathLike"] = __snapshots["isPathLike"] || {};
    __snapshots["isPathLike"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("isPathLike [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("isPathLike", __args);
  const second = __attempt("isPathLike", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("isPathLike [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("isPathLike", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("isPathLike [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("isPathLike", __args));
  const stored = __snapshots["isPathLike"] && __snapshots["isPathLike"][5];
  if (__capture || stored === undefined) {
    __snapshots["isPathLike"] = __snapshots["isPathLike"] || {};
    __snapshots["isPathLike"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("isPathLike [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("isPathLike", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("isPathLike [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("isPathLike", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("isKeyValue [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("isKeyValue", __args);
  const second = __attempt("isKeyValue", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("isKeyValue [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("isKeyValue", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("isKeyValue [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("isKeyValue", __args));
  const stored = __snapshots["isKeyValue"] && __snapshots["isKeyValue"][2];
  if (__capture || stored === undefined) {
    __snapshots["isKeyValue"] = __snapshots["isKeyValue"] || {};
    __snapshots["isKeyValue"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("isKeyValue [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("isKeyValue", __args);
  const second = __attempt("isKeyValue", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("isKeyValue [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("isKeyValue", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("isKeyValue [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("isKeyValue", __args));
  const stored = __snapshots["isKeyValue"] && __snapshots["isKeyValue"][5];
  if (__capture || stored === undefined) {
    __snapshots["isKeyValue"] = __snapshots["isKeyValue"] || {};
    __snapshots["isKeyValue"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("isKeyValue [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("isKeyValue", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("isKeyValue [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("isKeyValue", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolve [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("resolve", __args);
  const second = __attempt("resolve", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolve [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("resolve", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolve [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("resolve", __args));
  const stored = __snapshots["resolve"] && __snapshots["resolve"][2];
  if (__capture || stored === undefined) {
    __snapshots["resolve"] = __snapshots["resolve"] || {};
    __snapshots["resolve"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("resolve [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("resolve", __args);
  const second = __attempt("resolve", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolve [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("resolve", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolve [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("resolve", __args));
  const stored = __snapshots["resolve"] && __snapshots["resolve"][5];
  if (__capture || stored === undefined) {
    __snapshots["resolve"] = __snapshots["resolve"] || {};
    __snapshots["resolve"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("resolve [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("resolve", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolve [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("resolve", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildLookup [determinism] argset_0", () => {
  const __args = [[]];
  const first = __attempt("buildLookup", __args);
  const second = __attempt("buildLookup", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildLookup [immutability] argset_0", () => {
  const __args = [[]];
  const before = JSON.stringify(__args);
  const result = __attempt("buildLookup", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildLookup [snapshot] argset_0", () => {
  const __args = [[]];
  const actual = JSON.stringify(__attempt("buildLookup", __args));
  const stored = __snapshots["buildLookup"] && __snapshots["buildLookup"][2];
  if (__capture || stored === undefined) {
    __snapshots["buildLookup"] = __snapshots["buildLookup"] || {};
    __snapshots["buildLookup"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("buildLookup [determinism] argset_1", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("buildLookup", __args);
  const second = __attempt("buildLookup", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildLookup [immutability] argset_1", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("buildLookup", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildLookup [snapshot] argset_1", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("buildLookup", __args));
  const stored = __snapshots["buildLookup"] && __snapshots["buildLookup"][5];
  if (__capture || stored === undefined) {
    __snapshots["buildLookup"] = __snapshots["buildLookup"] || {};
    __snapshots["buildLookup"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("buildLookup [determinism] argset_2", () => {
  const __args = [[0]];
  const first = __attempt("buildLookup", __args);
  const second = __attempt("buildLookup", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildLookup [immutability] argset_2", () => {
  const __args = [[0]];
  const before = JSON.stringify(__args);
  const result = __attempt("buildLookup", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildLookup [snapshot] argset_2", () => {
  const __args = [[0]];
  const actual = JSON.stringify(__attempt("buildLookup", __args));
  const stored = __snapshots["buildLookup"] && __snapshots["buildLookup"][8];
  if (__capture || stored === undefined) {
    __snapshots["buildLookup"] = __snapshots["buildLookup"] || {};
    __snapshots["buildLookup"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("buildLookup [determinism] argset_3", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("buildLookup", __args);
  const second = __attempt("buildLookup", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("buildLookup [immutability] argset_3", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("buildLookup", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("buildLookup [snapshot] argset_3", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("buildLookup", __args));
  const stored = __snapshots["buildLookup"] && __snapshots["buildLookup"][11];
  if (__capture || stored === undefined) {
    __snapshots["buildLookup"] = __snapshots["buildLookup"] || {};
    __snapshots["buildLookup"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("buildLookup [edge_safety] edge_0", () => {
  const __args = [[]];
  try {
    __call("buildLookup", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("buildLookup [edge_safety] edge_1", () => {
  const __args = [[null]];
  try {
    __call("buildLookup", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

