// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_serialize_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_serialize_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_serialize_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("to_json [determinism] argset_0", () => {
  const __args = [{}, false];
  const first = __attempt("to_json", __args);
  const second = __attempt("to_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_json [immutability] argset_0", () => {
  const __args = [{}, false];
  const before = JSON.stringify(__args);
  const result = __attempt("to_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_json [snapshot] argset_0", () => {
  const __args = [{}, false];
  const actual = JSON.stringify(__attempt("to_json", __args));
  const stored = __snapshots["to_json"] && __snapshots["to_json"][2];
  if (__capture || stored === undefined) {
    __snapshots["to_json"] = __snapshots["to_json"] || {};
    __snapshots["to_json"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("to_json [determinism] argset_1", () => {
  const __args = [{"a": 1}, true];
  const first = __attempt("to_json", __args);
  const second = __attempt("to_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_json [immutability] argset_1", () => {
  const __args = [{"a": 1}, true];
  const before = JSON.stringify(__args);
  const result = __attempt("to_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_json [snapshot] argset_1", () => {
  const __args = [{"a": 1}, true];
  const actual = JSON.stringify(__attempt("to_json", __args));
  const stored = __snapshots["to_json"] && __snapshots["to_json"][5];
  if (__capture || stored === undefined) {
    __snapshots["to_json"] = __snapshots["to_json"] || {};
    __snapshots["to_json"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("to_json [determinism] argset_2", () => {
  const __args = [{"a": 1}, true];
  const first = __attempt("to_json", __args);
  const second = __attempt("to_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_json [immutability] argset_2", () => {
  const __args = [{"a": 1}, true];
  const before = JSON.stringify(__args);
  const result = __attempt("to_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_json [snapshot] argset_2", () => {
  const __args = [{"a": 1}, true];
  const actual = JSON.stringify(__attempt("to_json", __args));
  const stored = __snapshots["to_json"] && __snapshots["to_json"][8];
  if (__capture || stored === undefined) {
    __snapshots["to_json"] = __snapshots["to_json"] || {};
    __snapshots["to_json"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("to_json [edge_safety] edge_0", () => {
  const __args = [{}, false];
  try {
    __call("to_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_json [edge_safety] edge_1", () => {
  const __args = [{}, true];
  try {
    __call("to_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_json [edge_safety] edge_2", () => {
  const __args = [null, true];
  try {
    __call("to_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_json [edge_safety] edge_3", () => {
  const __args = [{"a": 1}, false];
  try {
    __call("to_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_json [edge_safety] edge_4", () => {
  const __args = [{"a": 1}, true];
  try {
    __call("to_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("from_json [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("from_json", __args);
  const second = __attempt("from_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("from_json [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("from_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("from_json [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("from_json", __args));
  const stored = __snapshots["from_json"] && __snapshots["from_json"][2];
  if (__capture || stored === undefined) {
    __snapshots["from_json"] = __snapshots["from_json"] || {};
    __snapshots["from_json"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("from_json [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("from_json", __args);
  const second = __attempt("from_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("from_json [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("from_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("from_json [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("from_json", __args));
  const stored = __snapshots["from_json"] && __snapshots["from_json"][5];
  if (__capture || stored === undefined) {
    __snapshots["from_json"] = __snapshots["from_json"] || {};
    __snapshots["from_json"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("from_json [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("from_json", __args);
  const second = __attempt("from_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("from_json [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("from_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("from_json [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("from_json", __args));
  const stored = __snapshots["from_json"] && __snapshots["from_json"][8];
  if (__capture || stored === undefined) {
    __snapshots["from_json"] = __snapshots["from_json"] || {};
    __snapshots["from_json"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("from_json [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("from_json", __args);
  const second = __attempt("from_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("from_json [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("from_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("from_json [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("from_json", __args));
  const stored = __snapshots["from_json"] && __snapshots["from_json"][11];
  if (__capture || stored === undefined) {
    __snapshots["from_json"] = __snapshots["from_json"] || {};
    __snapshots["from_json"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("from_json [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("from_json", __args);
  const second = __attempt("from_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("from_json [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("from_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("from_json [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("from_json", __args));
  const stored = __snapshots["from_json"] && __snapshots["from_json"][14];
  if (__capture || stored === undefined) {
    __snapshots["from_json"] = __snapshots["from_json"] || {};
    __snapshots["from_json"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("from_json [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("from_json", __args);
  const second = __attempt("from_json", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("from_json [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("from_json", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("from_json [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("from_json", __args));
  const stored = __snapshots["from_json"] && __snapshots["from_json"][17];
  if (__capture || stored === undefined) {
    __snapshots["from_json"] = __snapshots["from_json"] || {};
    __snapshots["from_json"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("from_json [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("from_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("from_json [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("from_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("from_json [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("from_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("from_json [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("from_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("from_json [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("from_json", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_markdown_table [determinism] argset_0", () => {
  const __args = [[], []];
  const first = __attempt("to_markdown_table", __args);
  const second = __attempt("to_markdown_table", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_markdown_table [immutability] argset_0", () => {
  const __args = [[], []];
  const before = JSON.stringify(__args);
  const result = __attempt("to_markdown_table", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_markdown_table [snapshot] argset_0", () => {
  const __args = [[], []];
  const actual = JSON.stringify(__attempt("to_markdown_table", __args));
  const stored = __snapshots["to_markdown_table"] && __snapshots["to_markdown_table"][2];
  if (__capture || stored === undefined) {
    __snapshots["to_markdown_table"] = __snapshots["to_markdown_table"] || {};
    __snapshots["to_markdown_table"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("to_markdown_table [determinism] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("to_markdown_table", __args);
  const second = __attempt("to_markdown_table", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_markdown_table [immutability] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("to_markdown_table", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_markdown_table [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("to_markdown_table", __args));
  const stored = __snapshots["to_markdown_table"] && __snapshots["to_markdown_table"][5];
  if (__capture || stored === undefined) {
    __snapshots["to_markdown_table"] = __snapshots["to_markdown_table"] || {};
    __snapshots["to_markdown_table"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("to_markdown_table [determinism] argset_2", () => {
  const __args = [[0], [0]];
  const first = __attempt("to_markdown_table", __args);
  const second = __attempt("to_markdown_table", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_markdown_table [immutability] argset_2", () => {
  const __args = [[0], [0]];
  const before = JSON.stringify(__args);
  const result = __attempt("to_markdown_table", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_markdown_table [snapshot] argset_2", () => {
  const __args = [[0], [0]];
  const actual = JSON.stringify(__attempt("to_markdown_table", __args));
  const stored = __snapshots["to_markdown_table"] && __snapshots["to_markdown_table"][8];
  if (__capture || stored === undefined) {
    __snapshots["to_markdown_table"] = __snapshots["to_markdown_table"] || {};
    __snapshots["to_markdown_table"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("to_markdown_table [determinism] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("to_markdown_table", __args);
  const second = __attempt("to_markdown_table", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_markdown_table [immutability] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("to_markdown_table", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_markdown_table [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("to_markdown_table", __args));
  const stored = __snapshots["to_markdown_table"] && __snapshots["to_markdown_table"][11];
  if (__capture || stored === undefined) {
    __snapshots["to_markdown_table"] = __snapshots["to_markdown_table"] || {};
    __snapshots["to_markdown_table"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("to_markdown_table [edge_safety] edge_0", () => {
  const __args = [[], []];
  try {
    __call("to_markdown_table", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_markdown_table [edge_safety] edge_1", () => {
  const __args = [[], [3, 1, 2]];
  try {
    __call("to_markdown_table", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_markdown_table [edge_safety] edge_2", () => {
  const __args = [[null], [3, 1, 2]];
  try {
    __call("to_markdown_table", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_markdown_table [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], []];
  try {
    __call("to_markdown_table", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_markdown_table [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], [null]];
  try {
    __call("to_markdown_table", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_plain_text [determinism] argset_0", () => {
  const __args = [{}];
  const first = __attempt("to_plain_text", __args);
  const second = __attempt("to_plain_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_plain_text [immutability] argset_0", () => {
  const __args = [{}];
  const before = JSON.stringify(__args);
  const result = __attempt("to_plain_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_plain_text [snapshot] argset_0", () => {
  const __args = [{}];
  const actual = JSON.stringify(__attempt("to_plain_text", __args));
  const stored = __snapshots["to_plain_text"] && __snapshots["to_plain_text"][2];
  if (__capture || stored === undefined) {
    __snapshots["to_plain_text"] = __snapshots["to_plain_text"] || {};
    __snapshots["to_plain_text"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("to_plain_text [determinism] argset_1", () => {
  const __args = [{"a": 1}];
  const first = __attempt("to_plain_text", __args);
  const second = __attempt("to_plain_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_plain_text [immutability] argset_1", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("to_plain_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_plain_text [snapshot] argset_1", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("to_plain_text", __args));
  const stored = __snapshots["to_plain_text"] && __snapshots["to_plain_text"][5];
  if (__capture || stored === undefined) {
    __snapshots["to_plain_text"] = __snapshots["to_plain_text"] || {};
    __snapshots["to_plain_text"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("to_plain_text [determinism] argset_2", () => {
  const __args = [{"a": 1}];
  const first = __attempt("to_plain_text", __args);
  const second = __attempt("to_plain_text", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("to_plain_text [immutability] argset_2", () => {
  const __args = [{"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("to_plain_text", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_plain_text [snapshot] argset_2", () => {
  const __args = [{"a": 1}];
  const actual = JSON.stringify(__attempt("to_plain_text", __args));
  const stored = __snapshots["to_plain_text"] && __snapshots["to_plain_text"][8];
  if (__capture || stored === undefined) {
    __snapshots["to_plain_text"] = __snapshots["to_plain_text"] || {};
    __snapshots["to_plain_text"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("to_plain_text [edge_safety] edge_0", () => {
  const __args = [{}];
  try {
    __call("to_plain_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_plain_text [edge_safety] edge_1", () => {
  const __args = [null];
  try {
    __call("to_plain_text", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

