// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_formula_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_formula_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_formula_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("column_to_index [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("column_to_index", __args);
  const second = __attempt("column_to_index", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("column_to_index [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("column_to_index", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("column_to_index [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("column_to_index", __args));
  const stored = __snapshots["column_to_index"] && __snapshots["column_to_index"][2];
  if (__capture || stored === undefined) {
    __snapshots["column_to_index"] = __snapshots["column_to_index"] || {};
    __snapshots["column_to_index"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("column_to_index [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("column_to_index", __args);
  const second = __attempt("column_to_index", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("column_to_index [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("column_to_index", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("column_to_index [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("column_to_index", __args));
  const stored = __snapshots["column_to_index"] && __snapshots["column_to_index"][5];
  if (__capture || stored === undefined) {
    __snapshots["column_to_index"] = __snapshots["column_to_index"] || {};
    __snapshots["column_to_index"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("column_to_index [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("column_to_index", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("column_to_index [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("column_to_index", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("index_to_column [determinism] argset_0", () => {
  const __args = [0];
  const first = __attempt("index_to_column", __args);
  const second = __attempt("index_to_column", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("index_to_column [immutability] argset_0", () => {
  const __args = [0];
  const before = JSON.stringify(__args);
  const result = __attempt("index_to_column", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("index_to_column [snapshot] argset_0", () => {
  const __args = [0];
  const actual = JSON.stringify(__attempt("index_to_column", __args));
  const stored = __snapshots["index_to_column"] && __snapshots["index_to_column"][2];
  if (__capture || stored === undefined) {
    __snapshots["index_to_column"] = __snapshots["index_to_column"] || {};
    __snapshots["index_to_column"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("index_to_column [determinism] argset_1", () => {
  const __args = [-1];
  const first = __attempt("index_to_column", __args);
  const second = __attempt("index_to_column", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("index_to_column [immutability] argset_1", () => {
  const __args = [-1];
  const before = JSON.stringify(__args);
  const result = __attempt("index_to_column", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("index_to_column [snapshot] argset_1", () => {
  const __args = [-1];
  const actual = JSON.stringify(__attempt("index_to_column", __args));
  const stored = __snapshots["index_to_column"] && __snapshots["index_to_column"][5];
  if (__capture || stored === undefined) {
    __snapshots["index_to_column"] = __snapshots["index_to_column"] || {};
    __snapshots["index_to_column"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("index_to_column [determinism] argset_2", () => {
  const __args = [42];
  const first = __attempt("index_to_column", __args);
  const second = __attempt("index_to_column", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("index_to_column [immutability] argset_2", () => {
  const __args = [42];
  const before = JSON.stringify(__args);
  const result = __attempt("index_to_column", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("index_to_column [snapshot] argset_2", () => {
  const __args = [42];
  const actual = JSON.stringify(__attempt("index_to_column", __args));
  const stored = __snapshots["index_to_column"] && __snapshots["index_to_column"][8];
  if (__capture || stored === undefined) {
    __snapshots["index_to_column"] = __snapshots["index_to_column"] || {};
    __snapshots["index_to_column"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("index_to_column [determinism] argset_3", () => {
  const __args = [3.14];
  const first = __attempt("index_to_column", __args);
  const second = __attempt("index_to_column", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("index_to_column [immutability] argset_3", () => {
  const __args = [3.14];
  const before = JSON.stringify(__args);
  const result = __attempt("index_to_column", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("index_to_column [snapshot] argset_3", () => {
  const __args = [3.14];
  const actual = JSON.stringify(__attempt("index_to_column", __args));
  const stored = __snapshots["index_to_column"] && __snapshots["index_to_column"][11];
  if (__capture || stored === undefined) {
    __snapshots["index_to_column"] = __snapshots["index_to_column"] || {};
    __snapshots["index_to_column"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("index_to_column [determinism] argset_4", () => {
  const __args = [42];
  const first = __attempt("index_to_column", __args);
  const second = __attempt("index_to_column", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("index_to_column [immutability] argset_4", () => {
  const __args = [42];
  const before = JSON.stringify(__args);
  const result = __attempt("index_to_column", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("index_to_column [snapshot] argset_4", () => {
  const __args = [42];
  const actual = JSON.stringify(__attempt("index_to_column", __args));
  const stored = __snapshots["index_to_column"] && __snapshots["index_to_column"][14];
  if (__capture || stored === undefined) {
    __snapshots["index_to_column"] = __snapshots["index_to_column"] || {};
    __snapshots["index_to_column"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("index_to_column [edge_safety] edge_0", () => {
  const __args = [0];
  try {
    __call("index_to_column", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("index_to_column [edge_safety] edge_1", () => {
  const __args = [-1];
  try {
    __call("index_to_column", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("index_to_column [edge_safety] edge_2", () => {
  const __args = [NaN];
  try {
    __call("index_to_column", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("index_to_column [edge_safety] edge_3", () => {
  const __args = [Infinity];
  try {
    __call("index_to_column", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("index_to_column [edge_safety] edge_4", () => {
  const __args = [-Infinity];
  try {
    __call("index_to_column", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("index_to_column [edge_safety] edge_5", () => {
  const __args = [65536];
  try {
    __call("index_to_column", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("expand_range [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("expand_range", __args);
  const second = __attempt("expand_range", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("expand_range [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("expand_range", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("expand_range [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("expand_range", __args));
  const stored = __snapshots["expand_range"] && __snapshots["expand_range"][2];
  if (__capture || stored === undefined) {
    __snapshots["expand_range"] = __snapshots["expand_range"] || {};
    __snapshots["expand_range"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("expand_range [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("expand_range", __args);
  const second = __attempt("expand_range", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("expand_range [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("expand_range", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("expand_range [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("expand_range", __args));
  const stored = __snapshots["expand_range"] && __snapshots["expand_range"][5];
  if (__capture || stored === undefined) {
    __snapshots["expand_range"] = __snapshots["expand_range"] || {};
    __snapshots["expand_range"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("expand_range [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("expand_range", __args);
  const second = __attempt("expand_range", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("expand_range [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("expand_range", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("expand_range [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("expand_range", __args));
  const stored = __snapshots["expand_range"] && __snapshots["expand_range"][8];
  if (__capture || stored === undefined) {
    __snapshots["expand_range"] = __snapshots["expand_range"] || {};
    __snapshots["expand_range"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("expand_range [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("expand_range", __args);
  const second = __attempt("expand_range", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("expand_range [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("expand_range", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("expand_range [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("expand_range", __args));
  const stored = __snapshots["expand_range"] && __snapshots["expand_range"][11];
  if (__capture || stored === undefined) {
    __snapshots["expand_range"] = __snapshots["expand_range"] || {};
    __snapshots["expand_range"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("expand_range [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("expand_range", __args);
  const second = __attempt("expand_range", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("expand_range [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("expand_range", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("expand_range [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("expand_range", __args));
  const stored = __snapshots["expand_range"] && __snapshots["expand_range"][14];
  if (__capture || stored === undefined) {
    __snapshots["expand_range"] = __snapshots["expand_range"] || {};
    __snapshots["expand_range"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("expand_range [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("expand_range", __args);
  const second = __attempt("expand_range", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("expand_range [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("expand_range", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("expand_range [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("expand_range", __args));
  const stored = __snapshots["expand_range"] && __snapshots["expand_range"][17];
  if (__capture || stored === undefined) {
    __snapshots["expand_range"] = __snapshots["expand_range"] || {};
    __snapshots["expand_range"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("expand_range [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("expand_range", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("expand_range [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("expand_range", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("expand_range [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("expand_range", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("expand_range [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("expand_range", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("expand_range [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("expand_range", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][2];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("tokenize [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("tokenize", __args);
  const second = __attempt("tokenize", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tokenize [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("tokenize", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tokenize [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("tokenize", __args));
  const stored = __snapshots["tokenize"] && __snapshots["tokenize"][5];
  if (__capture || stored === undefined) {
    __snapshots["tokenize"] = __snapshots["tokenize"] || {};
    __snapshots["tokenize"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("tokenize [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tokenize [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("tokenize", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate [determinism] argset_0", () => {
  const __args = ["seed_value", {}];
  const first = __attempt("evaluate", __args);
  const second = __attempt("evaluate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate [immutability] argset_0", () => {
  const __args = ["seed_value", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate [snapshot] argset_0", () => {
  const __args = ["seed_value", {}];
  const actual = JSON.stringify(__attempt("evaluate", __args));
  const stored = __snapshots["evaluate"] && __snapshots["evaluate"][2];
  if (__capture || stored === undefined) {
    __snapshots["evaluate"] = __snapshots["evaluate"] || {};
    __snapshots["evaluate"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("evaluate [determinism] argset_1", () => {
  const __args = ["seed_value", {"a": 1}];
  const first = __attempt("evaluate", __args);
  const second = __attempt("evaluate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate [immutability] argset_1", () => {
  const __args = ["seed_value", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate [snapshot] argset_1", () => {
  const __args = ["seed_value", {"a": 1}];
  const actual = JSON.stringify(__attempt("evaluate", __args));
  const stored = __snapshots["evaluate"] && __snapshots["evaluate"][5];
  if (__capture || stored === undefined) {
    __snapshots["evaluate"] = __snapshots["evaluate"] || {};
    __snapshots["evaluate"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("evaluate [determinism] argset_2", () => {
  const __args = ["seed_value", {"a": 1}];
  const first = __attempt("evaluate", __args);
  const second = __attempt("evaluate", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate [immutability] argset_2", () => {
  const __args = ["seed_value", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate [snapshot] argset_2", () => {
  const __args = ["seed_value", {"a": 1}];
  const actual = JSON.stringify(__attempt("evaluate", __args));
  const stored = __snapshots["evaluate"] && __snapshots["evaluate"][8];
  if (__capture || stored === undefined) {
    __snapshots["evaluate"] = __snapshots["evaluate"] || {};
    __snapshots["evaluate"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("evaluate [edge_safety] edge_0", () => {
  const __args = [null, {}];
  try {
    __call("evaluate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate [edge_safety] edge_1", () => {
  const __args = [null, {"a": 1}];
  try {
    __call("evaluate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate [edge_safety] edge_2", () => {
  const __args = [undefined, {"a": 1}];
  try {
    __call("evaluate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate [edge_safety] edge_3", () => {
  const __args = ["seed_value", {}];
  try {
    __call("evaluate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate [edge_safety] edge_4", () => {
  const __args = ["seed_value", null];
  try {
    __call("evaluate", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_formula [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("parse_formula", __args);
  const second = __attempt("parse_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_formula [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_formula [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("parse_formula", __args));
  const stored = __snapshots["parse_formula"] && __snapshots["parse_formula"][2];
  if (__capture || stored === undefined) {
    __snapshots["parse_formula"] = __snapshots["parse_formula"] || {};
    __snapshots["parse_formula"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("parse_formula [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("parse_formula", __args);
  const second = __attempt("parse_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_formula [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_formula [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("parse_formula", __args));
  const stored = __snapshots["parse_formula"] && __snapshots["parse_formula"][5];
  if (__capture || stored === undefined) {
    __snapshots["parse_formula"] = __snapshots["parse_formula"] || {};
    __snapshots["parse_formula"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("parse_formula [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("parse_formula", __args);
  const second = __attempt("parse_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_formula [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_formula [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("parse_formula", __args));
  const stored = __snapshots["parse_formula"] && __snapshots["parse_formula"][8];
  if (__capture || stored === undefined) {
    __snapshots["parse_formula"] = __snapshots["parse_formula"] || {};
    __snapshots["parse_formula"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("parse_formula [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("parse_formula", __args);
  const second = __attempt("parse_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_formula [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_formula [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("parse_formula", __args));
  const stored = __snapshots["parse_formula"] && __snapshots["parse_formula"][11];
  if (__capture || stored === undefined) {
    __snapshots["parse_formula"] = __snapshots["parse_formula"] || {};
    __snapshots["parse_formula"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("parse_formula [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("parse_formula", __args);
  const second = __attempt("parse_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_formula [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_formula [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("parse_formula", __args));
  const stored = __snapshots["parse_formula"] && __snapshots["parse_formula"][14];
  if (__capture || stored === undefined) {
    __snapshots["parse_formula"] = __snapshots["parse_formula"] || {};
    __snapshots["parse_formula"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("parse_formula [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("parse_formula", __args);
  const second = __attempt("parse_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_formula [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_formula [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("parse_formula", __args));
  const stored = __snapshots["parse_formula"] && __snapshots["parse_formula"][17];
  if (__capture || stored === undefined) {
    __snapshots["parse_formula"] = __snapshots["parse_formula"] || {};
    __snapshots["parse_formula"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("parse_formula [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("parse_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_formula [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("parse_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_formula [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("parse_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_formula [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("parse_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_formula [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("parse_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate_formula [determinism] argset_0", () => {
  const __args = ["alpha", {}];
  const first = __attempt("evaluate_formula", __args);
  const second = __attempt("evaluate_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate_formula [immutability] argset_0", () => {
  const __args = ["alpha", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate_formula [snapshot] argset_0", () => {
  const __args = ["alpha", {}];
  const actual = JSON.stringify(__attempt("evaluate_formula", __args));
  const stored = __snapshots["evaluate_formula"] && __snapshots["evaluate_formula"][2];
  if (__capture || stored === undefined) {
    __snapshots["evaluate_formula"] = __snapshots["evaluate_formula"] || {};
    __snapshots["evaluate_formula"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("evaluate_formula [determinism] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const first = __attempt("evaluate_formula", __args);
  const second = __attempt("evaluate_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate_formula [immutability] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate_formula [snapshot] argset_1", () => {
  const __args = ["hello world", {"a": 1}];
  const actual = JSON.stringify(__attempt("evaluate_formula", __args));
  const stored = __snapshots["evaluate_formula"] && __snapshots["evaluate_formula"][5];
  if (__capture || stored === undefined) {
    __snapshots["evaluate_formula"] = __snapshots["evaluate_formula"] || {};
    __snapshots["evaluate_formula"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("evaluate_formula [determinism] argset_2", () => {
  const __args = ["", {}];
  const first = __attempt("evaluate_formula", __args);
  const second = __attempt("evaluate_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate_formula [immutability] argset_2", () => {
  const __args = ["", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate_formula [snapshot] argset_2", () => {
  const __args = ["", {}];
  const actual = JSON.stringify(__attempt("evaluate_formula", __args));
  const stored = __snapshots["evaluate_formula"] && __snapshots["evaluate_formula"][8];
  if (__capture || stored === undefined) {
    __snapshots["evaluate_formula"] = __snapshots["evaluate_formula"] || {};
    __snapshots["evaluate_formula"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("evaluate_formula [determinism] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const first = __attempt("evaluate_formula", __args);
  const second = __attempt("evaluate_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate_formula [immutability] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate_formula [snapshot] argset_3", () => {
  const __args = ["  spaced  ", {"a": 1}];
  const actual = JSON.stringify(__attempt("evaluate_formula", __args));
  const stored = __snapshots["evaluate_formula"] && __snapshots["evaluate_formula"][11];
  if (__capture || stored === undefined) {
    __snapshots["evaluate_formula"] = __snapshots["evaluate_formula"] || {};
    __snapshots["evaluate_formula"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("evaluate_formula [determinism] argset_4", () => {
  const __args = ["Alpha42", {}];
  const first = __attempt("evaluate_formula", __args);
  const second = __attempt("evaluate_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate_formula [immutability] argset_4", () => {
  const __args = ["Alpha42", {}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate_formula [snapshot] argset_4", () => {
  const __args = ["Alpha42", {}];
  const actual = JSON.stringify(__attempt("evaluate_formula", __args));
  const stored = __snapshots["evaluate_formula"] && __snapshots["evaluate_formula"][14];
  if (__capture || stored === undefined) {
    __snapshots["evaluate_formula"] = __snapshots["evaluate_formula"] || {};
    __snapshots["evaluate_formula"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("evaluate_formula [determinism] argset_5", () => {
  const __args = ["", {"a": 1}];
  const first = __attempt("evaluate_formula", __args);
  const second = __attempt("evaluate_formula", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("evaluate_formula [immutability] argset_5", () => {
  const __args = ["", {"a": 1}];
  const before = JSON.stringify(__args);
  const result = __attempt("evaluate_formula", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("evaluate_formula [snapshot] argset_5", () => {
  const __args = ["", {"a": 1}];
  const actual = JSON.stringify(__attempt("evaluate_formula", __args));
  const stored = __snapshots["evaluate_formula"] && __snapshots["evaluate_formula"][17];
  if (__capture || stored === undefined) {
    __snapshots["evaluate_formula"] = __snapshots["evaluate_formula"] || {};
    __snapshots["evaluate_formula"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("evaluate_formula [edge_safety] edge_0", () => {
  const __args = ["", {}];
  try {
    __call("evaluate_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate_formula [edge_safety] edge_1", () => {
  const __args = ["", {"a": 1}];
  try {
    __call("evaluate_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate_formula [edge_safety] edge_2", () => {
  const __args = [" ", {"a": 1}];
  try {
    __call("evaluate_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate_formula [edge_safety] edge_3", () => {
  const __args = ["\t", {"a": 1}];
  try {
    __call("evaluate_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate_formula [edge_safety] edge_4", () => {
  const __args = ["0", {"a": 1}];
  try {
    __call("evaluate_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate_formula [edge_safety] edge_5", () => {
  const __args = ["null", {"a": 1}];
  try {
    __call("evaluate_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("evaluate_formula [edge_safety] edge_6", () => {
  const __args = ["", null];
  try {
    __call("evaluate_formula", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("format_result [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("format_result", __args);
  const second = __attempt("format_result", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_result [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("format_result", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_result [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("format_result", __args));
  const stored = __snapshots["format_result"] && __snapshots["format_result"][2];
  if (__capture || stored === undefined) {
    __snapshots["format_result"] = __snapshots["format_result"] || {};
    __snapshots["format_result"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("format_result [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("format_result", __args);
  const second = __attempt("format_result", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_result [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("format_result", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_result [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("format_result", __args));
  const stored = __snapshots["format_result"] && __snapshots["format_result"][5];
  if (__capture || stored === undefined) {
    __snapshots["format_result"] = __snapshots["format_result"] || {};
    __snapshots["format_result"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("format_result [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("format_result", __args);
  const second = __attempt("format_result", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_result [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("format_result", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_result [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("format_result", __args));
  const stored = __snapshots["format_result"] && __snapshots["format_result"][8];
  if (__capture || stored === undefined) {
    __snapshots["format_result"] = __snapshots["format_result"] || {};
    __snapshots["format_result"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("format_result [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("format_result", __args);
  const second = __attempt("format_result", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_result [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("format_result", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_result [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("format_result", __args));
  const stored = __snapshots["format_result"] && __snapshots["format_result"][11];
  if (__capture || stored === undefined) {
    __snapshots["format_result"] = __snapshots["format_result"] || {};
    __snapshots["format_result"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("format_result [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("format_result", __args);
  const second = __attempt("format_result", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_result [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("format_result", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_result [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("format_result", __args));
  const stored = __snapshots["format_result"] && __snapshots["format_result"][14];
  if (__capture || stored === undefined) {
    __snapshots["format_result"] = __snapshots["format_result"] || {};
    __snapshots["format_result"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("format_result [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("format_result", __args);
  const second = __attempt("format_result", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_result [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("format_result", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_result [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("format_result", __args));
  const stored = __snapshots["format_result"] && __snapshots["format_result"][17];
  if (__capture || stored === undefined) {
    __snapshots["format_result"] = __snapshots["format_result"] || {};
    __snapshots["format_result"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("format_result [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("format_result", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("format_result [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("format_result", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("format_result [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("format_result", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("format_result [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("format_result", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("format_result [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("format_result", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

