// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_parser_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_parser_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_parser_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("parse [determinism] argset_0", () => {
  const __args = [[]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_0", () => {
  const __args = [[]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_0", () => {
  const __args = [[]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][2];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("parse [determinism] argset_1", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_1", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_1", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][5];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("parse [determinism] argset_2", () => {
  const __args = [[0]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_2", () => {
  const __args = [[0]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_2", () => {
  const __args = [[0]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][8];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("parse [determinism] argset_3", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("parse", __args);
  const second = __attempt("parse", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse [immutability] argset_3", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("parse", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse [snapshot] argset_3", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("parse", __args));
  const stored = __snapshots["parse"] && __snapshots["parse"][11];
  if (__capture || stored === undefined) {
    __snapshots["parse"] = __snapshots["parse"] || {};
    __snapshots["parse"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("parse [edge_safety] edge_0", () => {
  const __args = [[]];
  try {
    __call("parse", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse [edge_safety] edge_1", () => {
  const __args = [[null]];
  try {
    __call("parse", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parseDirectives [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("parseDirectives", __args);
  const second = __attempt("parseDirectives", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parseDirectives [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("parseDirectives", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parseDirectives [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("parseDirectives", __args));
  const stored = __snapshots["parseDirectives"] && __snapshots["parseDirectives"][2];
  if (__capture || stored === undefined) {
    __snapshots["parseDirectives"] = __snapshots["parseDirectives"] || {};
    __snapshots["parseDirectives"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("parseDirectives [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("parseDirectives", __args);
  const second = __attempt("parseDirectives", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parseDirectives [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("parseDirectives", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parseDirectives [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("parseDirectives", __args));
  const stored = __snapshots["parseDirectives"] && __snapshots["parseDirectives"][5];
  if (__capture || stored === undefined) {
    __snapshots["parseDirectives"] = __snapshots["parseDirectives"] || {};
    __snapshots["parseDirectives"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("parseDirectives [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("parseDirectives", __args);
  const second = __attempt("parseDirectives", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parseDirectives [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parseDirectives", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parseDirectives [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("parseDirectives", __args));
  const stored = __snapshots["parseDirectives"] && __snapshots["parseDirectives"][8];
  if (__capture || stored === undefined) {
    __snapshots["parseDirectives"] = __snapshots["parseDirectives"] || {};
    __snapshots["parseDirectives"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("parseDirectives [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("parseDirectives", __args);
  const second = __attempt("parseDirectives", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parseDirectives [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("parseDirectives", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parseDirectives [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("parseDirectives", __args));
  const stored = __snapshots["parseDirectives"] && __snapshots["parseDirectives"][11];
  if (__capture || stored === undefined) {
    __snapshots["parseDirectives"] = __snapshots["parseDirectives"] || {};
    __snapshots["parseDirectives"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("parseDirectives [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("parseDirectives", __args);
  const second = __attempt("parseDirectives", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parseDirectives [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("parseDirectives", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parseDirectives [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("parseDirectives", __args));
  const stored = __snapshots["parseDirectives"] && __snapshots["parseDirectives"][14];
  if (__capture || stored === undefined) {
    __snapshots["parseDirectives"] = __snapshots["parseDirectives"] || {};
    __snapshots["parseDirectives"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("parseDirectives [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("parseDirectives", __args);
  const second = __attempt("parseDirectives", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parseDirectives [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parseDirectives", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parseDirectives [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("parseDirectives", __args));
  const stored = __snapshots["parseDirectives"] && __snapshots["parseDirectives"][17];
  if (__capture || stored === undefined) {
    __snapshots["parseDirectives"] = __snapshots["parseDirectives"] || {};
    __snapshots["parseDirectives"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("parseDirectives [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("parseDirectives", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parseDirectives [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("parseDirectives", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parseDirectives [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("parseDirectives", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parseDirectives [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("parseDirectives", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parseDirectives [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("parseDirectives", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("matchShape [determinism] argset_0", () => {
  const __args = [[], "seed_value"];
  const first = __attempt("matchShape", __args);
  const second = __attempt("matchShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("matchShape [immutability] argset_0", () => {
  const __args = [[], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("matchShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("matchShape [snapshot] argset_0", () => {
  const __args = [[], "seed_value"];
  const actual = JSON.stringify(__attempt("matchShape", __args));
  const stored = __snapshots["matchShape"] && __snapshots["matchShape"][2];
  if (__capture || stored === undefined) {
    __snapshots["matchShape"] = __snapshots["matchShape"] || {};
    __snapshots["matchShape"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("matchShape [determinism] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const first = __attempt("matchShape", __args);
  const second = __attempt("matchShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("matchShape [immutability] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("matchShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("matchShape [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const actual = JSON.stringify(__attempt("matchShape", __args));
  const stored = __snapshots["matchShape"] && __snapshots["matchShape"][5];
  if (__capture || stored === undefined) {
    __snapshots["matchShape"] = __snapshots["matchShape"] || {};
    __snapshots["matchShape"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("matchShape [determinism] argset_2", () => {
  const __args = [[0], "seed_value"];
  const first = __attempt("matchShape", __args);
  const second = __attempt("matchShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("matchShape [immutability] argset_2", () => {
  const __args = [[0], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("matchShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("matchShape [snapshot] argset_2", () => {
  const __args = [[0], "seed_value"];
  const actual = JSON.stringify(__attempt("matchShape", __args));
  const stored = __snapshots["matchShape"] && __snapshots["matchShape"][8];
  if (__capture || stored === undefined) {
    __snapshots["matchShape"] = __snapshots["matchShape"] || {};
    __snapshots["matchShape"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("matchShape [determinism] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const first = __attempt("matchShape", __args);
  const second = __attempt("matchShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("matchShape [immutability] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("matchShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("matchShape [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value"];
  const actual = JSON.stringify(__attempt("matchShape", __args));
  const stored = __snapshots["matchShape"] && __snapshots["matchShape"][11];
  if (__capture || stored === undefined) {
    __snapshots["matchShape"] = __snapshots["matchShape"] || {};
    __snapshots["matchShape"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("matchShape [edge_safety] edge_0", () => {
  const __args = [[], null];
  try {
    __call("matchShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("matchShape [edge_safety] edge_1", () => {
  const __args = [[], "seed_value"];
  try {
    __call("matchShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("matchShape [edge_safety] edge_2", () => {
  const __args = [[null], "seed_value"];
  try {
    __call("matchShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("matchShape [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], null];
  try {
    __call("matchShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("matchShape [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], undefined];
  try {
    __call("matchShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryShape [determinism] argset_0", () => {
  const __args = [[], "seed_value", "seed_value"];
  const first = __attempt("tryShape", __args);
  const second = __attempt("tryShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryShape [immutability] argset_0", () => {
  const __args = [[], "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("tryShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryShape [snapshot] argset_0", () => {
  const __args = [[], "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("tryShape", __args));
  const stored = __snapshots["tryShape"] && __snapshots["tryShape"][2];
  if (__capture || stored === undefined) {
    __snapshots["tryShape"] = __snapshots["tryShape"] || {};
    __snapshots["tryShape"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("tryShape [determinism] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value", "seed_value"];
  const first = __attempt("tryShape", __args);
  const second = __attempt("tryShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryShape [immutability] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("tryShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryShape [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("tryShape", __args));
  const stored = __snapshots["tryShape"] && __snapshots["tryShape"][5];
  if (__capture || stored === undefined) {
    __snapshots["tryShape"] = __snapshots["tryShape"] || {};
    __snapshots["tryShape"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("tryShape [determinism] argset_2", () => {
  const __args = [[0], "seed_value", "seed_value"];
  const first = __attempt("tryShape", __args);
  const second = __attempt("tryShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryShape [immutability] argset_2", () => {
  const __args = [[0], "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("tryShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryShape [snapshot] argset_2", () => {
  const __args = [[0], "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("tryShape", __args));
  const stored = __snapshots["tryShape"] && __snapshots["tryShape"][8];
  if (__capture || stored === undefined) {
    __snapshots["tryShape"] = __snapshots["tryShape"] || {};
    __snapshots["tryShape"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("tryShape [determinism] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value", "seed_value"];
  const first = __attempt("tryShape", __args);
  const second = __attempt("tryShape", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("tryShape [immutability] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("tryShape", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("tryShape [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("tryShape", __args));
  const stored = __snapshots["tryShape"] && __snapshots["tryShape"][11];
  if (__capture || stored === undefined) {
    __snapshots["tryShape"] = __snapshots["tryShape"] || {};
    __snapshots["tryShape"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("tryShape [edge_safety] edge_0", () => {
  const __args = [[], null, null];
  try {
    __call("tryShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryShape [edge_safety] edge_1", () => {
  const __args = [[], "seed_value", "seed_value"];
  try {
    __call("tryShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryShape [edge_safety] edge_2", () => {
  const __args = [[null], "seed_value", "seed_value"];
  try {
    __call("tryShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryShape [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], null, "seed_value"];
  try {
    __call("tryShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryShape [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], undefined, "seed_value"];
  try {
    __call("tryShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryShape [edge_safety] edge_5", () => {
  const __args = [[3, 1, 2], "seed_value", null];
  try {
    __call("tryShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("tryShape [edge_safety] edge_6", () => {
  const __args = [[3, 1, 2], "seed_value", undefined];
  try {
    __call("tryShape", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

