// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_resolver_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_resolver_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_resolver_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("resolve [determinism] argset_0", () => {
  const __args = ["seed_value"];
  const first = __attempt("resolve", __args);
  const second = __attempt("resolve", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolve [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("resolve", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolve [snapshot] argset_0", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("resolve", __args));
  const stored = __snapshots["resolve"] && __snapshots["resolve"][2];
  if (__capture || stored === undefined) {
    __snapshots["resolve"] = __snapshots["resolve"] || {};
    __snapshots["resolve"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("resolve [determinism] argset_1", () => {
  const __args = ["seed_value"];
  const first = __attempt("resolve", __args);
  const second = __attempt("resolve", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("resolve [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("resolve", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("resolve [snapshot] argset_1", () => {
  const __args = ["seed_value"];
  const actual = JSON.stringify(__attempt("resolve", __args));
  const stored = __snapshots["resolve"] && __snapshots["resolve"][5];
  if (__capture || stored === undefined) {
    __snapshots["resolve"] = __snapshots["resolve"] || {};
    __snapshots["resolve"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("resolve [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("resolve", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("resolve [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("resolve", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [determinism] argset_0", () => {
  const __args = ["seed_value", 0];
  const first = __attempt("nodeId", __args);
  const second = __attempt("nodeId", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("nodeId [immutability] argset_0", () => {
  const __args = ["seed_value", 0];
  const before = JSON.stringify(__args);
  const result = __attempt("nodeId", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("nodeId [snapshot] argset_0", () => {
  const __args = ["seed_value", 0];
  const actual = JSON.stringify(__attempt("nodeId", __args));
  const stored = __snapshots["nodeId"] && __snapshots["nodeId"][2];
  if (__capture || stored === undefined) {
    __snapshots["nodeId"] = __snapshots["nodeId"] || {};
    __snapshots["nodeId"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("nodeId [determinism] argset_1", () => {
  const __args = ["seed_value", -1];
  const first = __attempt("nodeId", __args);
  const second = __attempt("nodeId", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("nodeId [immutability] argset_1", () => {
  const __args = ["seed_value", -1];
  const before = JSON.stringify(__args);
  const result = __attempt("nodeId", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("nodeId [snapshot] argset_1", () => {
  const __args = ["seed_value", -1];
  const actual = JSON.stringify(__attempt("nodeId", __args));
  const stored = __snapshots["nodeId"] && __snapshots["nodeId"][5];
  if (__capture || stored === undefined) {
    __snapshots["nodeId"] = __snapshots["nodeId"] || {};
    __snapshots["nodeId"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("nodeId [determinism] argset_2", () => {
  const __args = ["seed_value", 42];
  const first = __attempt("nodeId", __args);
  const second = __attempt("nodeId", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("nodeId [immutability] argset_2", () => {
  const __args = ["seed_value", 42];
  const before = JSON.stringify(__args);
  const result = __attempt("nodeId", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("nodeId [snapshot] argset_2", () => {
  const __args = ["seed_value", 42];
  const actual = JSON.stringify(__attempt("nodeId", __args));
  const stored = __snapshots["nodeId"] && __snapshots["nodeId"][8];
  if (__capture || stored === undefined) {
    __snapshots["nodeId"] = __snapshots["nodeId"] || {};
    __snapshots["nodeId"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("nodeId [determinism] argset_3", () => {
  const __args = ["seed_value", 3.14];
  const first = __attempt("nodeId", __args);
  const second = __attempt("nodeId", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("nodeId [immutability] argset_3", () => {
  const __args = ["seed_value", 3.14];
  const before = JSON.stringify(__args);
  const result = __attempt("nodeId", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("nodeId [snapshot] argset_3", () => {
  const __args = ["seed_value", 3.14];
  const actual = JSON.stringify(__attempt("nodeId", __args));
  const stored = __snapshots["nodeId"] && __snapshots["nodeId"][11];
  if (__capture || stored === undefined) {
    __snapshots["nodeId"] = __snapshots["nodeId"] || {};
    __snapshots["nodeId"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("nodeId [determinism] argset_4", () => {
  const __args = ["seed_value", 42];
  const first = __attempt("nodeId", __args);
  const second = __attempt("nodeId", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("nodeId [immutability] argset_4", () => {
  const __args = ["seed_value", 42];
  const before = JSON.stringify(__args);
  const result = __attempt("nodeId", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("nodeId [snapshot] argset_4", () => {
  const __args = ["seed_value", 42];
  const actual = JSON.stringify(__attempt("nodeId", __args));
  const stored = __snapshots["nodeId"] && __snapshots["nodeId"][14];
  if (__capture || stored === undefined) {
    __snapshots["nodeId"] = __snapshots["nodeId"] || {};
    __snapshots["nodeId"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("nodeId [edge_safety] edge_0", () => {
  const __args = [null, 0];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_1", () => {
  const __args = [null, 42];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_2", () => {
  const __args = [undefined, 42];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_3", () => {
  const __args = ["seed_value", 0];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_4", () => {
  const __args = ["seed_value", -1];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_5", () => {
  const __args = ["seed_value", NaN];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_6", () => {
  const __args = ["seed_value", Infinity];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_7", () => {
  const __args = ["seed_value", -Infinity];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("nodeId [edge_safety] edge_8", () => {
  const __args = ["seed_value", 65536];
  try {
    __call("nodeId", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detectCycle [determinism] argset_0", () => {
  const __args = [[], []];
  const first = __attempt("detectCycle", __args);
  const second = __attempt("detectCycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detectCycle [immutability] argset_0", () => {
  const __args = [[], []];
  const before = JSON.stringify(__args);
  const result = __attempt("detectCycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detectCycle [snapshot] argset_0", () => {
  const __args = [[], []];
  const actual = JSON.stringify(__attempt("detectCycle", __args));
  const stored = __snapshots["detectCycle"] && __snapshots["detectCycle"][2];
  if (__capture || stored === undefined) {
    __snapshots["detectCycle"] = __snapshots["detectCycle"] || {};
    __snapshots["detectCycle"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("detectCycle [determinism] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("detectCycle", __args);
  const second = __attempt("detectCycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detectCycle [immutability] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("detectCycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detectCycle [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("detectCycle", __args));
  const stored = __snapshots["detectCycle"] && __snapshots["detectCycle"][5];
  if (__capture || stored === undefined) {
    __snapshots["detectCycle"] = __snapshots["detectCycle"] || {};
    __snapshots["detectCycle"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("detectCycle [determinism] argset_2", () => {
  const __args = [[0], [0]];
  const first = __attempt("detectCycle", __args);
  const second = __attempt("detectCycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detectCycle [immutability] argset_2", () => {
  const __args = [[0], [0]];
  const before = JSON.stringify(__args);
  const result = __attempt("detectCycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detectCycle [snapshot] argset_2", () => {
  const __args = [[0], [0]];
  const actual = JSON.stringify(__attempt("detectCycle", __args));
  const stored = __snapshots["detectCycle"] && __snapshots["detectCycle"][8];
  if (__capture || stored === undefined) {
    __snapshots["detectCycle"] = __snapshots["detectCycle"] || {};
    __snapshots["detectCycle"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("detectCycle [determinism] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("detectCycle", __args);
  const second = __attempt("detectCycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detectCycle [immutability] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("detectCycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detectCycle [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("detectCycle", __args));
  const stored = __snapshots["detectCycle"] && __snapshots["detectCycle"][11];
  if (__capture || stored === undefined) {
    __snapshots["detectCycle"] = __snapshots["detectCycle"] || {};
    __snapshots["detectCycle"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("detectCycle [edge_safety] edge_0", () => {
  const __args = [[], []];
  try {
    __call("detectCycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detectCycle [edge_safety] edge_1", () => {
  const __args = [[], [3, 1, 2]];
  try {
    __call("detectCycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detectCycle [edge_safety] edge_2", () => {
  const __args = [[null], [3, 1, 2]];
  try {
    __call("detectCycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detectCycle [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], []];
  try {
    __call("detectCycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detectCycle [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], [null]];
  try {
    __call("detectCycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

