// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_topo_sort_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_topo_sort_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_topo_sort_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("topological_sort [determinism] argset_0", () => {
  const __args = [[], []];
  const first = __attempt("topological_sort", __args);
  const second = __attempt("topological_sort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topological_sort [immutability] argset_0", () => {
  const __args = [[], []];
  const before = JSON.stringify(__args);
  const result = __attempt("topological_sort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topological_sort [snapshot] argset_0", () => {
  const __args = [[], []];
  const actual = JSON.stringify(__attempt("topological_sort", __args));
  const stored = __snapshots["topological_sort"] && __snapshots["topological_sort"][2];
  if (__capture || stored === undefined) {
    __snapshots["topological_sort"] = __snapshots["topological_sort"] || {};
    __snapshots["topological_sort"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("topological_sort [determinism] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("topological_sort", __args);
  const second = __attempt("topological_sort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topological_sort [immutability] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("topological_sort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topological_sort [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("topological_sort", __args));
  const stored = __snapshots["topological_sort"] && __snapshots["topological_sort"][5];
  if (__capture || stored === undefined) {
    __snapshots["topological_sort"] = __snapshots["topological_sort"] || {};
    __snapshots["topological_sort"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("topological_sort [determinism] argset_2", () => {
  const __args = [[0], [0]];
  const first = __attempt("topological_sort", __args);
  const second = __attempt("topological_sort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topological_sort [immutability] argset_2", () => {
  const __args = [[0], [0]];
  const before = JSON.stringify(__args);
  const result = __attempt("topological_sort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topological_sort [snapshot] argset_2", () => {
  const __args = [[0], [0]];
  const actual = JSON.stringify(__attempt("topological_sort", __args));
  const stored = __snapshots["topological_sort"] && __snapshots["topological_sort"][8];
  if (__capture || stored === undefined) {
    __snapshots["topological_sort"] = __snapshots["topological_sort"] || {};
    __snapshots["topological_sort"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("topological_sort [determinism] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("topological_sort", __args);
  const second = __attempt("topological_sort", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("topological_sort [immutability] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("topological_sort", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("topological_sort [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("topological_sort", __args));
  const stored = __snapshots["topological_sort"] && __snapshots["topological_sort"][11];
  if (__capture || stored === undefined) {
    __snapshots["topological_sort"] = __snapshots["topological_sort"] || {};
    __snapshots["topological_sort"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("topological_sort [edge_safety] edge_0", () => {
  const __args = [[], []];
  try {
    __call("topological_sort", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("topological_sort [edge_safety] edge_1", () => {
  const __args = [[], [3, 1, 2]];
  try {
    __call("topological_sort", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("topological_sort [edge_safety] edge_2", () => {
  const __args = [[null], [3, 1, 2]];
  try {
    __call("topological_sort", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("topological_sort [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], []];
  try {
    __call("topological_sort", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("topological_sort [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], [null]];
  try {
    __call("topological_sort", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detect_cycle [determinism] argset_0", () => {
  const __args = [[], []];
  const first = __attempt("detect_cycle", __args);
  const second = __attempt("detect_cycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detect_cycle [immutability] argset_0", () => {
  const __args = [[], []];
  const before = JSON.stringify(__args);
  const result = __attempt("detect_cycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detect_cycle [snapshot] argset_0", () => {
  const __args = [[], []];
  const actual = JSON.stringify(__attempt("detect_cycle", __args));
  const stored = __snapshots["detect_cycle"] && __snapshots["detect_cycle"][2];
  if (__capture || stored === undefined) {
    __snapshots["detect_cycle"] = __snapshots["detect_cycle"] || {};
    __snapshots["detect_cycle"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("detect_cycle [determinism] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("detect_cycle", __args);
  const second = __attempt("detect_cycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detect_cycle [immutability] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("detect_cycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detect_cycle [snapshot] argset_1", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("detect_cycle", __args));
  const stored = __snapshots["detect_cycle"] && __snapshots["detect_cycle"][5];
  if (__capture || stored === undefined) {
    __snapshots["detect_cycle"] = __snapshots["detect_cycle"] || {};
    __snapshots["detect_cycle"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("detect_cycle [determinism] argset_2", () => {
  const __args = [[0], [0]];
  const first = __attempt("detect_cycle", __args);
  const second = __attempt("detect_cycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detect_cycle [immutability] argset_2", () => {
  const __args = [[0], [0]];
  const before = JSON.stringify(__args);
  const result = __attempt("detect_cycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detect_cycle [snapshot] argset_2", () => {
  const __args = [[0], [0]];
  const actual = JSON.stringify(__attempt("detect_cycle", __args));
  const stored = __snapshots["detect_cycle"] && __snapshots["detect_cycle"][8];
  if (__capture || stored === undefined) {
    __snapshots["detect_cycle"] = __snapshots["detect_cycle"] || {};
    __snapshots["detect_cycle"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("detect_cycle [determinism] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const first = __attempt("detect_cycle", __args);
  const second = __attempt("detect_cycle", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("detect_cycle [immutability] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("detect_cycle", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("detect_cycle [snapshot] argset_3", () => {
  const __args = [[3, 1, 2], [3, 1, 2]];
  const actual = JSON.stringify(__attempt("detect_cycle", __args));
  const stored = __snapshots["detect_cycle"] && __snapshots["detect_cycle"][11];
  if (__capture || stored === undefined) {
    __snapshots["detect_cycle"] = __snapshots["detect_cycle"] || {};
    __snapshots["detect_cycle"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("detect_cycle [edge_safety] edge_0", () => {
  const __args = [[], []];
  try {
    __call("detect_cycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detect_cycle [edge_safety] edge_1", () => {
  const __args = [[], [3, 1, 2]];
  try {
    __call("detect_cycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detect_cycle [edge_safety] edge_2", () => {
  const __args = [[null], [3, 1, 2]];
  try {
    __call("detect_cycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detect_cycle [edge_safety] edge_3", () => {
  const __args = [[3, 1, 2], []];
  try {
    __call("detect_cycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("detect_cycle [edge_safety] edge_4", () => {
  const __args = [[3, 1, 2], [null]];
  try {
    __call("detect_cycle", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

