// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_pmi_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_pmi_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_pmi_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

const __ctor = mod;
let __instance = null;
try { __instance = new __ctor(); } catch (__e0) { try { __instance = new __ctor({}); } catch (__e1) {} }
function __call(name, args) {
  if (__instance === null) throw new Error("target unavailable: constructor rejected no-arg and object-arg instantiation");
  if (typeof __instance[name] !== "function") throw new Error("missing method " + name);
  return __instance[name].apply(__instance, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("execute [determinism] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][2];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("execute [determinism] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const first = __attempt("execute", __args);
  const second = __attempt("execute", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("execute [immutability] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("execute", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("execute [snapshot] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("execute", __args));
  const stored = __snapshots["execute"] && __snapshots["execute"][5];
  if (__capture || stored === undefined) {
    __snapshots["execute"] = __snapshots["execute"] || {};
    __snapshots["execute"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("execute [edge_safety] edge_0", () => {
  const __args = [null, null, null];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_1", () => {
  const __args = [null, "seed_value", "seed_value"];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_2", () => {
  const __args = [undefined, "seed_value", "seed_value"];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_3", () => {
  const __args = ["seed_value", null, "seed_value"];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_4", () => {
  const __args = ["seed_value", undefined, "seed_value"];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_5", () => {
  const __args = ["seed_value", "seed_value", null];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("execute [edge_safety] edge_6", () => {
  const __args = ["seed_value", "seed_value", undefined];
  try {
    __call("execute", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [determinism] argset_0", () => {
  const __args = [0, 0, 0, 0];
  const first = __attempt("executeFromCounts", __args);
  const second = __attempt("executeFromCounts", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeFromCounts [immutability] argset_0", () => {
  const __args = [0, 0, 0, 0];
  const before = JSON.stringify(__args);
  const result = __attempt("executeFromCounts", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeFromCounts [snapshot] argset_0", () => {
  const __args = [0, 0, 0, 0];
  const actual = JSON.stringify(__attempt("executeFromCounts", __args));
  const stored = __snapshots["executeFromCounts"] && __snapshots["executeFromCounts"][2];
  if (__capture || stored === undefined) {
    __snapshots["executeFromCounts"] = __snapshots["executeFromCounts"] || {};
    __snapshots["executeFromCounts"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("executeFromCounts [determinism] argset_1", () => {
  const __args = [-1, -1, -1, -1];
  const first = __attempt("executeFromCounts", __args);
  const second = __attempt("executeFromCounts", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeFromCounts [immutability] argset_1", () => {
  const __args = [-1, -1, -1, -1];
  const before = JSON.stringify(__args);
  const result = __attempt("executeFromCounts", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeFromCounts [snapshot] argset_1", () => {
  const __args = [-1, -1, -1, -1];
  const actual = JSON.stringify(__attempt("executeFromCounts", __args));
  const stored = __snapshots["executeFromCounts"] && __snapshots["executeFromCounts"][5];
  if (__capture || stored === undefined) {
    __snapshots["executeFromCounts"] = __snapshots["executeFromCounts"] || {};
    __snapshots["executeFromCounts"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("executeFromCounts [determinism] argset_2", () => {
  const __args = [42, 42, 42, 42];
  const first = __attempt("executeFromCounts", __args);
  const second = __attempt("executeFromCounts", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeFromCounts [immutability] argset_2", () => {
  const __args = [42, 42, 42, 42];
  const before = JSON.stringify(__args);
  const result = __attempt("executeFromCounts", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeFromCounts [snapshot] argset_2", () => {
  const __args = [42, 42, 42, 42];
  const actual = JSON.stringify(__attempt("executeFromCounts", __args));
  const stored = __snapshots["executeFromCounts"] && __snapshots["executeFromCounts"][8];
  if (__capture || stored === undefined) {
    __snapshots["executeFromCounts"] = __snapshots["executeFromCounts"] || {};
    __snapshots["executeFromCounts"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("executeFromCounts [determinism] argset_3", () => {
  const __args = [3.14, 3.14, 3.14, 3.14];
  const first = __attempt("executeFromCounts", __args);
  const second = __attempt("executeFromCounts", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeFromCounts [immutability] argset_3", () => {
  const __args = [3.14, 3.14, 3.14, 3.14];
  const before = JSON.stringify(__args);
  const result = __attempt("executeFromCounts", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeFromCounts [snapshot] argset_3", () => {
  const __args = [3.14, 3.14, 3.14, 3.14];
  const actual = JSON.stringify(__attempt("executeFromCounts", __args));
  const stored = __snapshots["executeFromCounts"] && __snapshots["executeFromCounts"][11];
  if (__capture || stored === undefined) {
    __snapshots["executeFromCounts"] = __snapshots["executeFromCounts"] || {};
    __snapshots["executeFromCounts"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("executeFromCounts [determinism] argset_4", () => {
  const __args = [42, 42, 42, 42];
  const first = __attempt("executeFromCounts", __args);
  const second = __attempt("executeFromCounts", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeFromCounts [immutability] argset_4", () => {
  const __args = [42, 42, 42, 42];
  const before = JSON.stringify(__args);
  const result = __attempt("executeFromCounts", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeFromCounts [snapshot] argset_4", () => {
  const __args = [42, 42, 42, 42];
  const actual = JSON.stringify(__attempt("executeFromCounts", __args));
  const stored = __snapshots["executeFromCounts"] && __snapshots["executeFromCounts"][14];
  if (__capture || stored === undefined) {
    __snapshots["executeFromCounts"] = __snapshots["executeFromCounts"] || {};
    __snapshots["executeFromCounts"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("executeFromCounts [edge_safety] edge_0", () => {
  const __args = [0, 0, 0, 0];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_1", () => {
  const __args = [0, 42, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_2", () => {
  const __args = [-1, 42, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_3", () => {
  const __args = [NaN, 42, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_4", () => {
  const __args = [Infinity, 42, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_5", () => {
  const __args = [-Infinity, 42, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_6", () => {
  const __args = [65536, 42, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_7", () => {
  const __args = [42, 0, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_8", () => {
  const __args = [42, -1, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_9", () => {
  const __args = [42, NaN, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_10", () => {
  const __args = [42, Infinity, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_11", () => {
  const __args = [42, -Infinity, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_12", () => {
  const __args = [42, 65536, 42, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_13", () => {
  const __args = [42, 42, 0, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_14", () => {
  const __args = [42, 42, -1, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_15", () => {
  const __args = [42, 42, NaN, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_16", () => {
  const __args = [42, 42, Infinity, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_17", () => {
  const __args = [42, 42, -Infinity, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_18", () => {
  const __args = [42, 42, 65536, 42];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_19", () => {
  const __args = [42, 42, 42, 0];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_20", () => {
  const __args = [42, 42, 42, -1];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_21", () => {
  const __args = [42, 42, 42, NaN];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_22", () => {
  const __args = [42, 42, 42, Infinity];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_23", () => {
  const __args = [42, 42, 42, -Infinity];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeFromCounts [edge_safety] edge_24", () => {
  const __args = [42, 42, 42, 65536];
  try {
    __call("executeFromCounts", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeNormalized [determinism] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const first = __attempt("executeNormalized", __args);
  const second = __attempt("executeNormalized", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeNormalized [immutability] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("executeNormalized", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeNormalized [snapshot] argset_0", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("executeNormalized", __args));
  const stored = __snapshots["executeNormalized"] && __snapshots["executeNormalized"][2];
  if (__capture || stored === undefined) {
    __snapshots["executeNormalized"] = __snapshots["executeNormalized"] || {};
    __snapshots["executeNormalized"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("executeNormalized [determinism] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const first = __attempt("executeNormalized", __args);
  const second = __attempt("executeNormalized", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("executeNormalized [immutability] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("executeNormalized", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("executeNormalized [snapshot] argset_1", () => {
  const __args = ["seed_value", "seed_value", "seed_value"];
  const actual = JSON.stringify(__attempt("executeNormalized", __args));
  const stored = __snapshots["executeNormalized"] && __snapshots["executeNormalized"][5];
  if (__capture || stored === undefined) {
    __snapshots["executeNormalized"] = __snapshots["executeNormalized"] || {};
    __snapshots["executeNormalized"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("executeNormalized [edge_safety] edge_0", () => {
  const __args = [null, null, null];
  try {
    __call("executeNormalized", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeNormalized [edge_safety] edge_1", () => {
  const __args = [null, "seed_value", "seed_value"];
  try {
    __call("executeNormalized", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeNormalized [edge_safety] edge_2", () => {
  const __args = [undefined, "seed_value", "seed_value"];
  try {
    __call("executeNormalized", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeNormalized [edge_safety] edge_3", () => {
  const __args = ["seed_value", null, "seed_value"];
  try {
    __call("executeNormalized", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeNormalized [edge_safety] edge_4", () => {
  const __args = ["seed_value", undefined, "seed_value"];
  try {
    __call("executeNormalized", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeNormalized [edge_safety] edge_5", () => {
  const __args = ["seed_value", "seed_value", null];
  try {
    __call("executeNormalized", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("executeNormalized [edge_safety] edge_6", () => {
  const __args = ["seed_value", "seed_value", undefined];
  try {
    __call("executeNormalized", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

