// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_time_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\code_shared_time_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__code_shared_time_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("utc_now [edge_safety] edge_0", () => {
  const __args = [];
  try {
    __call("utc_now", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("format_duration [determinism] argset_0", () => {
  const __args = [[]];
  const first = __attempt("format_duration", __args);
  const second = __attempt("format_duration", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_duration [immutability] argset_0", () => {
  const __args = [[]];
  const before = JSON.stringify(__args);
  const result = __attempt("format_duration", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_duration [snapshot] argset_0", () => {
  const __args = [[]];
  const actual = JSON.stringify(__attempt("format_duration", __args));
  const stored = __snapshots["format_duration"] && __snapshots["format_duration"][2];
  if (__capture || stored === undefined) {
    __snapshots["format_duration"] = __snapshots["format_duration"] || {};
    __snapshots["format_duration"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("format_duration [determinism] argset_1", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("format_duration", __args);
  const second = __attempt("format_duration", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_duration [immutability] argset_1", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("format_duration", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_duration [snapshot] argset_1", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("format_duration", __args));
  const stored = __snapshots["format_duration"] && __snapshots["format_duration"][5];
  if (__capture || stored === undefined) {
    __snapshots["format_duration"] = __snapshots["format_duration"] || {};
    __snapshots["format_duration"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("format_duration [determinism] argset_2", () => {
  const __args = [[0]];
  const first = __attempt("format_duration", __args);
  const second = __attempt("format_duration", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_duration [immutability] argset_2", () => {
  const __args = [[0]];
  const before = JSON.stringify(__args);
  const result = __attempt("format_duration", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_duration [snapshot] argset_2", () => {
  const __args = [[0]];
  const actual = JSON.stringify(__attempt("format_duration", __args));
  const stored = __snapshots["format_duration"] && __snapshots["format_duration"][8];
  if (__capture || stored === undefined) {
    __snapshots["format_duration"] = __snapshots["format_duration"] || {};
    __snapshots["format_duration"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("format_duration [determinism] argset_3", () => {
  const __args = [[3, 1, 2]];
  const first = __attempt("format_duration", __args);
  const second = __attempt("format_duration", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("format_duration [immutability] argset_3", () => {
  const __args = [[3, 1, 2]];
  const before = JSON.stringify(__args);
  const result = __attempt("format_duration", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("format_duration [snapshot] argset_3", () => {
  const __args = [[3, 1, 2]];
  const actual = JSON.stringify(__attempt("format_duration", __args));
  const stored = __snapshots["format_duration"] && __snapshots["format_duration"][11];
  if (__capture || stored === undefined) {
    __snapshots["format_duration"] = __snapshots["format_duration"] || {};
    __snapshots["format_duration"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("format_duration [edge_safety] edge_0", () => {
  const __args = [[]];
  try {
    __call("format_duration", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("format_duration [edge_safety] edge_1", () => {
  const __args = [[null]];
  try {
    __call("format_duration", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_iso [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_iso", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_iso [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_iso", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_iso [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_iso", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_iso [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_iso", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_iso [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_iso", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_iso [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_iso", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_iso [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("parse_iso", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_iso [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("parse_iso", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_iso [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("parse_iso", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_iso [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("parse_iso", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_iso [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("parse_iso", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_timestamp [immutability] argset_0", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("to_timestamp", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_timestamp [immutability] argset_1", () => {
  const __args = ["seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("to_timestamp", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("to_timestamp [edge_safety] edge_0", () => {
  const __args = [null];
  try {
    __call("to_timestamp", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("to_timestamp [edge_safety] edge_1", () => {
  const __args = [undefined];
  try {
    __call("to_timestamp", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

