// AUTOGENERATED by pipeline system_validate_and_test_code_shared_v2 for code_shared_code_inspector_v2_2_0_draft
// regenerate instead of editing
const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const mod = require("E:\\root_0dot1_wip\\shared_v2\\code\\utilities\\test_generation\\code_shared_code_inspector_v2_2_0_draft.js");
const SNAPSHOT_DIR = __dirname;
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, "snapshots/utilities__test_generation__code_shared_code_inspector_v2_2_0_draft.snap.json");
const __capture = process.env.TESTGEN_CAPTURE === "1";
let __snapshots = {};
if (fs.existsSync(SNAPSHOT_PATH)) {
  __snapshots = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
}
let __dirty = false;

function __serialize(value) {
  if (value === undefined) return "__undefined__";
  if (typeof value === "number" && !Number.isFinite(value)) return "__" + String(value) + "__";
  if (typeof value === "function") return "__function__";
  try { return JSON.stringify(value); } catch (error) { return "__unserializable__"; }
}

function __attempt(name, args) {
  try {
    return { threw: false, value: __serialize(__call(name, args)) };
  } catch (error) {
    const label = error && error.constructor ? error.constructor.name : String(error);
    return { threw: true, value: "__threw__:" + label + ":" + ((error && error.message) || "") };
  }
}

function __call(name, args) {
  if (typeof mod[name] !== "function") throw new Error("missing export " + name);
  return mod[name].apply(null, args);
}

process.on("exit", function () {
  if (__dirty) fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(__snapshots, null, 2));
});

test("split_top_level [determinism] argset_0", () => {
  const __args = ["alpha", "seed_value"];
  const first = __attempt("split_top_level", __args);
  const second = __attempt("split_top_level", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("split_top_level [immutability] argset_0", () => {
  const __args = ["alpha", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("split_top_level", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("split_top_level [snapshot] argset_0", () => {
  const __args = ["alpha", "seed_value"];
  const actual = JSON.stringify(__attempt("split_top_level", __args));
  const stored = __snapshots["split_top_level"] && __snapshots["split_top_level"][2];
  if (__capture || stored === undefined) {
    __snapshots["split_top_level"] = __snapshots["split_top_level"] || {};
    __snapshots["split_top_level"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("split_top_level [determinism] argset_1", () => {
  const __args = ["hello world", "seed_value"];
  const first = __attempt("split_top_level", __args);
  const second = __attempt("split_top_level", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("split_top_level [immutability] argset_1", () => {
  const __args = ["hello world", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("split_top_level", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("split_top_level [snapshot] argset_1", () => {
  const __args = ["hello world", "seed_value"];
  const actual = JSON.stringify(__attempt("split_top_level", __args));
  const stored = __snapshots["split_top_level"] && __snapshots["split_top_level"][5];
  if (__capture || stored === undefined) {
    __snapshots["split_top_level"] = __snapshots["split_top_level"] || {};
    __snapshots["split_top_level"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("split_top_level [determinism] argset_2", () => {
  const __args = ["", "seed_value"];
  const first = __attempt("split_top_level", __args);
  const second = __attempt("split_top_level", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("split_top_level [immutability] argset_2", () => {
  const __args = ["", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("split_top_level", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("split_top_level [snapshot] argset_2", () => {
  const __args = ["", "seed_value"];
  const actual = JSON.stringify(__attempt("split_top_level", __args));
  const stored = __snapshots["split_top_level"] && __snapshots["split_top_level"][8];
  if (__capture || stored === undefined) {
    __snapshots["split_top_level"] = __snapshots["split_top_level"] || {};
    __snapshots["split_top_level"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("split_top_level [determinism] argset_3", () => {
  const __args = ["  spaced  ", "seed_value"];
  const first = __attempt("split_top_level", __args);
  const second = __attempt("split_top_level", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("split_top_level [immutability] argset_3", () => {
  const __args = ["  spaced  ", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("split_top_level", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("split_top_level [snapshot] argset_3", () => {
  const __args = ["  spaced  ", "seed_value"];
  const actual = JSON.stringify(__attempt("split_top_level", __args));
  const stored = __snapshots["split_top_level"] && __snapshots["split_top_level"][11];
  if (__capture || stored === undefined) {
    __snapshots["split_top_level"] = __snapshots["split_top_level"] || {};
    __snapshots["split_top_level"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("split_top_level [determinism] argset_4", () => {
  const __args = ["Alpha42", "seed_value"];
  const first = __attempt("split_top_level", __args);
  const second = __attempt("split_top_level", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("split_top_level [immutability] argset_4", () => {
  const __args = ["Alpha42", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("split_top_level", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("split_top_level [snapshot] argset_4", () => {
  const __args = ["Alpha42", "seed_value"];
  const actual = JSON.stringify(__attempt("split_top_level", __args));
  const stored = __snapshots["split_top_level"] && __snapshots["split_top_level"][14];
  if (__capture || stored === undefined) {
    __snapshots["split_top_level"] = __snapshots["split_top_level"] || {};
    __snapshots["split_top_level"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("split_top_level [determinism] argset_5", () => {
  const __args = ["", "seed_value"];
  const first = __attempt("split_top_level", __args);
  const second = __attempt("split_top_level", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("split_top_level [immutability] argset_5", () => {
  const __args = ["", "seed_value"];
  const before = JSON.stringify(__args);
  const result = __attempt("split_top_level", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("split_top_level [snapshot] argset_5", () => {
  const __args = ["", "seed_value"];
  const actual = JSON.stringify(__attempt("split_top_level", __args));
  const stored = __snapshots["split_top_level"] && __snapshots["split_top_level"][17];
  if (__capture || stored === undefined) {
    __snapshots["split_top_level"] = __snapshots["split_top_level"] || {};
    __snapshots["split_top_level"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("split_top_level [edge_safety] edge_0", () => {
  const __args = ["", null];
  try {
    __call("split_top_level", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("split_top_level [edge_safety] edge_1", () => {
  const __args = ["", "seed_value"];
  try {
    __call("split_top_level", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("split_top_level [edge_safety] edge_2", () => {
  const __args = [" ", "seed_value"];
  try {
    __call("split_top_level", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("split_top_level [edge_safety] edge_3", () => {
  const __args = ["\t", "seed_value"];
  try {
    __call("split_top_level", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("split_top_level [edge_safety] edge_4", () => {
  const __args = ["0", "seed_value"];
  try {
    __call("split_top_level", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("split_top_level [edge_safety] edge_5", () => {
  const __args = ["null", "seed_value"];
  try {
    __call("split_top_level", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("split_top_level [edge_safety] edge_6", () => {
  const __args = ["", undefined];
  try {
    __call("split_top_level", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_params [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("parse_params", __args);
  const second = __attempt("parse_params", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_params [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_params", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_params [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("parse_params", __args));
  const stored = __snapshots["parse_params"] && __snapshots["parse_params"][2];
  if (__capture || stored === undefined) {
    __snapshots["parse_params"] = __snapshots["parse_params"] || {};
    __snapshots["parse_params"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("parse_params [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("parse_params", __args);
  const second = __attempt("parse_params", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_params [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_params", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_params [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("parse_params", __args));
  const stored = __snapshots["parse_params"] && __snapshots["parse_params"][5];
  if (__capture || stored === undefined) {
    __snapshots["parse_params"] = __snapshots["parse_params"] || {};
    __snapshots["parse_params"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("parse_params [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("parse_params", __args);
  const second = __attempt("parse_params", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_params [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_params", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_params [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("parse_params", __args));
  const stored = __snapshots["parse_params"] && __snapshots["parse_params"][8];
  if (__capture || stored === undefined) {
    __snapshots["parse_params"] = __snapshots["parse_params"] || {};
    __snapshots["parse_params"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("parse_params [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("parse_params", __args);
  const second = __attempt("parse_params", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_params [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_params", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_params [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("parse_params", __args));
  const stored = __snapshots["parse_params"] && __snapshots["parse_params"][11];
  if (__capture || stored === undefined) {
    __snapshots["parse_params"] = __snapshots["parse_params"] || {};
    __snapshots["parse_params"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("parse_params [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("parse_params", __args);
  const second = __attempt("parse_params", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_params [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_params", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_params [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("parse_params", __args));
  const stored = __snapshots["parse_params"] && __snapshots["parse_params"][14];
  if (__capture || stored === undefined) {
    __snapshots["parse_params"] = __snapshots["parse_params"] || {};
    __snapshots["parse_params"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("parse_params [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("parse_params", __args);
  const second = __attempt("parse_params", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("parse_params [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("parse_params", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("parse_params [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("parse_params", __args));
  const stored = __snapshots["parse_params"] && __snapshots["parse_params"][17];
  if (__capture || stored === undefined) {
    __snapshots["parse_params"] = __snapshots["parse_params"] || {};
    __snapshots["parse_params"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("parse_params [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("parse_params", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_params [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("parse_params", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_params [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("parse_params", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_params [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("parse_params", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("parse_params [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("parse_params", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("inspect_source", __args);
  const second = __attempt("inspect_source", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("inspect_source", __args));
  const stored = __snapshots["inspect_source"] && __snapshots["inspect_source"][2];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source"] = __snapshots["inspect_source"] || {};
    __snapshots["inspect_source"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("inspect_source [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("inspect_source", __args);
  const second = __attempt("inspect_source", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("inspect_source", __args));
  const stored = __snapshots["inspect_source"] && __snapshots["inspect_source"][5];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source"] = __snapshots["inspect_source"] || {};
    __snapshots["inspect_source"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("inspect_source [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("inspect_source", __args);
  const second = __attempt("inspect_source", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("inspect_source", __args));
  const stored = __snapshots["inspect_source"] && __snapshots["inspect_source"][8];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source"] = __snapshots["inspect_source"] || {};
    __snapshots["inspect_source"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("inspect_source [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("inspect_source", __args);
  const second = __attempt("inspect_source", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("inspect_source", __args));
  const stored = __snapshots["inspect_source"] && __snapshots["inspect_source"][11];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source"] = __snapshots["inspect_source"] || {};
    __snapshots["inspect_source"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("inspect_source [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("inspect_source", __args);
  const second = __attempt("inspect_source", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("inspect_source", __args));
  const stored = __snapshots["inspect_source"] && __snapshots["inspect_source"][14];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source"] = __snapshots["inspect_source"] || {};
    __snapshots["inspect_source"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("inspect_source [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("inspect_source", __args);
  const second = __attempt("inspect_source", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("inspect_source", __args));
  const stored = __snapshots["inspect_source"] && __snapshots["inspect_source"][17];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source"] = __snapshots["inspect_source"] || {};
    __snapshots["inspect_source"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("inspect_source [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("inspect_source", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("inspect_source", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("inspect_source", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("inspect_source", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("inspect_source", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_ast [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("inspect_source_ast", __args);
  const second = __attempt("inspect_source_ast", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_ast [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_ast", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_ast [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("inspect_source_ast", __args));
  const stored = __snapshots["inspect_source_ast"] && __snapshots["inspect_source_ast"][2];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_ast"] = __snapshots["inspect_source_ast"] || {};
    __snapshots["inspect_source_ast"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("inspect_source_ast [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("inspect_source_ast", __args);
  const second = __attempt("inspect_source_ast", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_ast [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_ast", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_ast [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("inspect_source_ast", __args));
  const stored = __snapshots["inspect_source_ast"] && __snapshots["inspect_source_ast"][5];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_ast"] = __snapshots["inspect_source_ast"] || {};
    __snapshots["inspect_source_ast"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("inspect_source_ast [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("inspect_source_ast", __args);
  const second = __attempt("inspect_source_ast", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_ast [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_ast", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_ast [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("inspect_source_ast", __args));
  const stored = __snapshots["inspect_source_ast"] && __snapshots["inspect_source_ast"][8];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_ast"] = __snapshots["inspect_source_ast"] || {};
    __snapshots["inspect_source_ast"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("inspect_source_ast [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("inspect_source_ast", __args);
  const second = __attempt("inspect_source_ast", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_ast [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_ast", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_ast [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("inspect_source_ast", __args));
  const stored = __snapshots["inspect_source_ast"] && __snapshots["inspect_source_ast"][11];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_ast"] = __snapshots["inspect_source_ast"] || {};
    __snapshots["inspect_source_ast"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("inspect_source_ast [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("inspect_source_ast", __args);
  const second = __attempt("inspect_source_ast", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_ast [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_ast", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_ast [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("inspect_source_ast", __args));
  const stored = __snapshots["inspect_source_ast"] && __snapshots["inspect_source_ast"][14];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_ast"] = __snapshots["inspect_source_ast"] || {};
    __snapshots["inspect_source_ast"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("inspect_source_ast [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("inspect_source_ast", __args);
  const second = __attempt("inspect_source_ast", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_ast [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_ast", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_ast [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("inspect_source_ast", __args));
  const stored = __snapshots["inspect_source_ast"] && __snapshots["inspect_source_ast"][17];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_ast"] = __snapshots["inspect_source_ast"] || {};
    __snapshots["inspect_source_ast"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("inspect_source_ast [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("inspect_source_ast", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_ast [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("inspect_source_ast", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_ast [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("inspect_source_ast", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_ast [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("inspect_source_ast", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_ast [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("inspect_source_ast", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_auto [determinism] argset_0", () => {
  const __args = ["alpha"];
  const first = __attempt("inspect_source_auto", __args);
  const second = __attempt("inspect_source_auto", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_auto [immutability] argset_0", () => {
  const __args = ["alpha"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_auto", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_auto [snapshot] argset_0", () => {
  const __args = ["alpha"];
  const actual = JSON.stringify(__attempt("inspect_source_auto", __args));
  const stored = __snapshots["inspect_source_auto"] && __snapshots["inspect_source_auto"][2];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_auto"] = __snapshots["inspect_source_auto"] || {};
    __snapshots["inspect_source_auto"][2] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 2");
  }
});

test("inspect_source_auto [determinism] argset_1", () => {
  const __args = ["hello world"];
  const first = __attempt("inspect_source_auto", __args);
  const second = __attempt("inspect_source_auto", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_auto [immutability] argset_1", () => {
  const __args = ["hello world"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_auto", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_auto [snapshot] argset_1", () => {
  const __args = ["hello world"];
  const actual = JSON.stringify(__attempt("inspect_source_auto", __args));
  const stored = __snapshots["inspect_source_auto"] && __snapshots["inspect_source_auto"][5];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_auto"] = __snapshots["inspect_source_auto"] || {};
    __snapshots["inspect_source_auto"][5] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 5");
  }
});

test("inspect_source_auto [determinism] argset_2", () => {
  const __args = [""];
  const first = __attempt("inspect_source_auto", __args);
  const second = __attempt("inspect_source_auto", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_auto [immutability] argset_2", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_auto", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_auto [snapshot] argset_2", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("inspect_source_auto", __args));
  const stored = __snapshots["inspect_source_auto"] && __snapshots["inspect_source_auto"][8];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_auto"] = __snapshots["inspect_source_auto"] || {};
    __snapshots["inspect_source_auto"][8] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 8");
  }
});

test("inspect_source_auto [determinism] argset_3", () => {
  const __args = ["  spaced  "];
  const first = __attempt("inspect_source_auto", __args);
  const second = __attempt("inspect_source_auto", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_auto [immutability] argset_3", () => {
  const __args = ["  spaced  "];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_auto", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_auto [snapshot] argset_3", () => {
  const __args = ["  spaced  "];
  const actual = JSON.stringify(__attempt("inspect_source_auto", __args));
  const stored = __snapshots["inspect_source_auto"] && __snapshots["inspect_source_auto"][11];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_auto"] = __snapshots["inspect_source_auto"] || {};
    __snapshots["inspect_source_auto"][11] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 11");
  }
});

test("inspect_source_auto [determinism] argset_4", () => {
  const __args = ["Alpha42"];
  const first = __attempt("inspect_source_auto", __args);
  const second = __attempt("inspect_source_auto", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_auto [immutability] argset_4", () => {
  const __args = ["Alpha42"];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_auto", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_auto [snapshot] argset_4", () => {
  const __args = ["Alpha42"];
  const actual = JSON.stringify(__attempt("inspect_source_auto", __args));
  const stored = __snapshots["inspect_source_auto"] && __snapshots["inspect_source_auto"][14];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_auto"] = __snapshots["inspect_source_auto"] || {};
    __snapshots["inspect_source_auto"][14] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 14");
  }
});

test("inspect_source_auto [determinism] argset_5", () => {
  const __args = [""];
  const first = __attempt("inspect_source_auto", __args);
  const second = __attempt("inspect_source_auto", __args);
  assert.deepStrictEqual(second, first, "nondeterministic behaviour");
});

test("inspect_source_auto [immutability] argset_5", () => {
  const __args = [""];
  const before = JSON.stringify(__args);
  const result = __attempt("inspect_source_auto", __args);
  if (result.threw === false) {
    const after = JSON.stringify(__args);
    assert.strictEqual(after, before, "input arguments were mutated");
  }
});

test("inspect_source_auto [snapshot] argset_5", () => {
  const __args = [""];
  const actual = JSON.stringify(__attempt("inspect_source_auto", __args));
  const stored = __snapshots["inspect_source_auto"] && __snapshots["inspect_source_auto"][17];
  if (__capture || stored === undefined) {
    __snapshots["inspect_source_auto"] = __snapshots["inspect_source_auto"] || {};
    __snapshots["inspect_source_auto"][17] = actual;
    __dirty = true;
  } else {
    assert.strictEqual(actual, stored, "snapshot mismatch for case 17");
  }
});

test("inspect_source_auto [edge_safety] edge_0", () => {
  const __args = [""];
  try {
    __call("inspect_source_auto", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_auto [edge_safety] edge_1", () => {
  const __args = [" "];
  try {
    __call("inspect_source_auto", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_auto [edge_safety] edge_2", () => {
  const __args = ["\t"];
  try {
    __call("inspect_source_auto", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_auto [edge_safety] edge_3", () => {
  const __args = ["0"];
  try {
    __call("inspect_source_auto", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

test("inspect_source_auto [edge_safety] edge_4", () => {
  const __args = ["null"];
  try {
    __call("inspect_source_auto", __args);
  } catch (error) {
    assert.ok(error instanceof Error, "threw non Error value: " + String(error));
  }
});

